export const mockRes = {
    resourceData: {
        'id': 'api.resoucebundles.read',
        'ver': '1.0',
        'ts': '2018-06-28 06:18:39:455+0000',
        'params': {
            'resmsgid': '191b76f0-7a9b-11e8-9b77-a7a606cb2ef9',
            'msgid': null,
            'status': 'successful',
            'err': '',
            'errmsg': ''
        },
        'responseCode': 'OK',
        'result': {
            'frmelmnts': {
                'btn': {
                    'add': 'ADD',
                    'yes': 'YES',
                    'no': 'NO',
                    'ok': 'OK',
                    'cancel': 'CANCEL',
                    'save': 'SAVE',
                    'resume': 'RESUME',
                    'update': 'UPDATE',
                    'clear': 'CLEAR',
                    'publish': 'PUBLISH',
                    'reject': 'REJECT',
                    'tryagain': 'TRY AGAIN',
                    'close': 'CLOSE',
                    'accept': 'ACCEPT',
                    'discard': 'DISCARD',
                    'startcreating': 'START CREATING',
                    'tcyes': 'Yes',
                    'requestChanges': 'REQUEST CHANGES',
                    'tcno': 'No',
                    'edit': 'EDIT',
                    'submit': 'SUBMIT',
                    'download': 'DOWNLOAD',
                    'apply': 'APPLY',
                    'reset': 'RESET',
                    'smplcsv': 'DOWNLOAD SAMPLE CSV',
                    'uploadorgscsv': 'UPLOAD ORGANIZATIONS CSV',
                    'uploadusrscsv': 'UPLOAD USERS CSV',
                    'chksts': 'CHECK STATUS',
                    'approve': 'APPROVE',
                    'tcok': 'Ok',
                    'viewless': 'VIEW LESS',
                    'viewmore': 'VIEW MORE',
                    'finish': 'FINISH',
                    'signup': 'SIGN UP',
                    'login': 'LOGIN',
                    'back': 'BACK',
                    'anncmntgotit': 'GOT IT',
                    'anncmntconfirmrecipients': 'CONFIRM RECIPIENTS',
                    'anncmntpreview': 'PREVIEW ANNOUNCEMENT',
                    'anncmntsendanncmnt': 'SEND ANNOUNCEMENT',
                    'anncmntselectrecipients': 'SELECT RECIPIENTS',
                    'anncmnteditrecipients': 'EDIT RECIPIENTS',
                    'anncmntdtlsview': 'VIEW',
                    'yesiamsure': 'YES, IM SURE\t',
                    'enroll': 'Enroll\t',
                    'create': 'CREATE\t',
                    'copylink': 'COPY LINK\t',
                    'first': 'FIRST\t',
                    'previous': 'PREVIOUS\t',
                    'next': 'NEXT\t',
                    'last': 'LAST\t',
                    'resumecourse': 'RESUME COURSE\t',
                    'viewcoursestats': 'VIEW COURSE STATS'
                },
                'bdge': {
                    'course': 'Course'
                },
                'lbl': {
                    'tcyes': 'Yes',
                    'tcno': 'No',
                    'tcfrom': 'From',
                    'tcto': 'To',
                    'title': 'Title',
                    'description': 'Description',
                    'takenote': 'TAKE NOTE',
                    'addnote': 'ADD NOTE',
                    'mynotebook': 'My Notebook',
                    'mynotes': 'My Notes',
                    'search': 'Search',
                    'edit': 'Edit',
                    'delete': 'Delete',
                    'deletenote': 'Delete Note',
                    'yes': 'YES',
                    'no': 'NO',
                    'batches': 'Batches',
                    'insertimage': 'Insert Image',
                    'textbook': 'Book',
                    'textbookdescription': 'Build books using resources for an interesting learning experience.',
                    'course': 'Course',
                    'coursedescription': '',
                    'lesson': 'Resource',
                    'lessondescription': '',
                    'collection': 'Collection',
                    'collectiondescription': 'Compile resources of your choice.',
                    'lessonplandescription': 'Frame lesson plans with structured sections for an efficient learning experience.',
                    'lessonplan': 'Lesson Plan',
                    'contentupload': 'Upload Content',
                    'contentuploaddescription': 'You can upload content here.',
                    'createlessontext': 'Create Resource',
                    'name': 'Name',
                    'lessonfillater': 'These details can be filled when adding content to Resource.',
                    'createcollection': 'Create Collection',
                    'collectionfillater': 'These details can be filled when adding content to Collection.',
                    'createtextbook': 'Create Book',
                    'bookfillater': 'These details can be filled when adding content to Book.',
                    'createlessonplan': 'Create Lesson Plan',
                    'lpfilllater': 'These details can be filled when adding content to Lesson Plan.',
                    'designcourse': 'Design Course',
                    'coursefilllater': 'These details can be filled when adding content to Course.',
                    'author': 'Author',
                    'medium': 'Medium',
                    'class': 'Class',
                    'credits': 'Credits',
                    'subject': 'Subject',
                    'lastupdate': 'Last update',
                    'createdon': 'Created On',
                    'status': 'Status',
                    'flaggedreason': 'Flagged reason',
                    'flaggedby': 'Flagged by',
                    'flaggeddescription': 'Flagged Description',
                    'contentinformation': 'Content Information',
                    'concept': 'Concepts',
                    'curriculum': 'Curriculum',
                    'keywords': 'Keywords',
                    'agreeandproceedtext': 'All content created and uploaded here will be licensed under CC-BY 4.0.',
                    'deletecontent': 'Delete Content',
                    'deleteconfirm': 'Are you sure to delete this content?',
                    'deletepublishedcontent': 'Retire Content',
                    'deletepublishedconfirm': 'Retire myself from the content?',
                    'viewworkspace': 'View your workspace',
                    'resourcetype': 'Resource Type',
                    'experience': 'Experience',
                    'worktitle': 'Occupation / Work Title',
                    'designation': 'Designation',
                    'organization': 'Organization',
                    'subjectstaught': 'Subject(s) taught',
                    'iscurrentjob': 'Is this your current job',
                    'address': 'Address',
                    'seladdresstype': 'Select Address Type',
                    'permanent': 'Permanent',
                    'current': 'Current',
                    'addressline1': 'Address Line 1',
                    'addressline2': 'Address Line 2',
                    'city': 'City',
                    'state': 'State',
                    'country': 'Country',
                    'pincode': 'Pin Code',
                    'education': 'Education',
                    'degree': 'Degree',
                    'yop': 'Year of Passing',
                    'institute': 'Institution Name',
                    'grade': 'Grade',
                    'percentage': 'Percentage',
                    'board': 'Board/University',
                    'addlInfo': 'Additional Information',
                    'email': 'Email ID',
                    'phone': 'Phone number',
                    'gender': 'Gender',
                    'language': 'Language(s) known',
                    'birthdate': 'Birthdate (dd/mm/yyyy)',
                    'subjects': 'Subjects of expertise',
                    'contents': 'Contents',
                    'currentlocation': 'Current location',
                    'grades': 'Grades',
                    'socialmedia': 'Social media',
                    'facebook': 'Facebook',
                    'twitter': 'Twitter',
                    'linkedIn': 'LinkedIn',
                    'blog': 'Blog',
                    'whatwentwrong': 'What went wrong?',
                    'whatwentwrongdesc': '',
                    'contentname': 'CONTENT NAME',
                    'selectreason': 'SELECT A REASON',
                    'share': 'Share',
                    'sharelink': 'Share by the link -',
                    'batchname': 'NAME OF BATCH',
                    'aboutbatch': 'ABOUT THIS BATCH',
                    'startdate': 'START DATE',
                    'enddate': 'END DATE',
                    'natureofbatch': 'BATCH TYPE',
                    'bacthmembers': 'MEMBERS IN THE BATCH',
                    'batchmentors': 'MENTORS IN THE BATCH',
                    'batchparticipants': 'SELECTED PARTICIPANTS',
                    'batchselmentors': 'SELECTED MENTORS',
                    'inactive': 'Inactive',
                    'active': 'Active',
                    'blocked': 'Blocked',
                    'retired': 'Retired',
                    'filters': 'Filters',
                    'filterby': 'Filter by',
                    'sort': 'Sort',
                    'chkuploadsts': 'Check Upload Status',
                    'upldfile': 'Uploaded File',
                    'processid': 'Process ID',
                    'provider': 'OrgProvider',
                    'extlid': 'OrgExternalId',
                    'orgid': 'OrgId',
                    'successres': 'Success Results',
                    'failres': 'Failure Results',
                    'confmblk': 'Are you sure to Block',
                    'selrole': 'Select Role',
                    'org': 'Org',
                    'assgnbdge': 'Assign Badge',
                    'cnfmassgn': 'Do you want to assign',
                    'orgtypes': 'Organization Type',
                    'addorgtype': 'Add Organization Type',
                    'updateorgtype': 'Update Organization Type',
                    'confirmblock': 'Are you sure to Block',
                    'confirmassign': 'Do you want to assign',
                    'jobProfile': 'Experience',
                    'avatar': 'Profile picture',
                    'profileSummary': 'Profile description',
                    'firstName': 'First name',
                    'lastName': 'Last name',
                    'skillTags': 'Skill Tags',
                    'addSkills': 'Add Skills',
                    'username': 'User Name',
                    'password': 'Password',
                    'phonenumber': 'Phone Number',
                    'dob': 'Date Of Birth',
                    'lang': 'Language',
                    'languages': 'Bengali,English,Gujarati,Hindi,Kannada,Marathi,Punjabi,Tamil,Telugu',
                    'page': 'Page',
                    'tryagain': 'Try Again',
                    'close': 'Close',
                    'createnewanncmnt': 'Create New Announcement',
                    'createnewanncmntdesc': 'Fill in all the required fields to create the announcement.',
                    'resendanncmntdesc': 'You can make any edits required and resend the announcement.',
                    'selectrecipient': 'Select Announcement Recipients',
                    'selectrecipientdesc': 'Select locations who should receive the announcement.',
                    'editrecipientdesc': 'Edit locations who should receive the announcement.',
                    'confirmrecipient': 'Confirm Announcement Recipients',
                    'confirmrecipientdesc': 'Review and confirm your announcement recipients.',
                    'previewanncmnt': 'Preview Announcement',
                    'previewanncmntdesc': 'This is how your announcement will look.',
                    'anncmntstep': 'STEP',
                    'anncmnttitle': 'TITLE',
                    'anncmntfrom': 'FROM',
                    'anncmntfromDesc': 'Please enter organisation/department that has sent the announcement',
                    'anncmnttype': 'ANNOUNCEMENT TYPE',
                    'anncmntdesc': 'DESCRIPTION (OPTIONAL)',
                    'anncmntlink': 'URL / WEBLINK',
                    'anncmntaddlink': 'Add URL/weblink',
                    'anncmntaddlinkdesc': '(For example, you can link a Google Form)',
                    'anncmntaddmorelink': 'Add Another URL/weblink',
                    'anncmntuploadfile': 'UPLOAD ATTACHMENT',
                    'anncmntsentsuccess': 'Announcement Sent!',
                    'anncmntsentdesc': '',
                    'anncmntdtlsweblinks': 'Weblinks',
                    'anncmntdtlsattachments': 'Attachments',
                    'anncmntdtlssenton': 'Sent on',
                    'anncmntcancel': 'Are you sure you want to stop creating this announcement',
                    'anncmntcanceldesc': 'You will lose your work if you close this announcement',
                    'anncmntresentmsg': 'Announcement Resent',
                    'anncmntresentmsgdesc': 'Your announcement has been resent to all the choosen recipients.',
                    'anncmntall': 'All Announcements',
                    'anncmntmine': 'My Announcements',
                    'anncmntreadmore': '... Read More',
                    'anncmntcreate': 'CREATE ANNOUNCEMENT',
                    'anncmntsent': 'Showing all sent announcements',
                    'anncmntnotfound': 'No announcement found!',
                    'anncmntplzcreate': 'Please create announcement',
                    'anncmntlastupdate': 'Consumption data last updated on',
                    'anncmntcancelconfirm': 'Are you sure you want to stop showing this announcement?',
                    'anncmntcancelconfirmdescrption': 'Users will not be able to see this announcement after this action.',
                    'anncmnttblname': 'Name',
                    'anncmnttblpublished': 'Published',
                    'anncmnttblsent': 'Sent',
                    'anncmnttblreceived': 'Received',
                    'anncmnttblseen': 'Seen',
                    'anncmnttblactions': 'Actions',
                    'anncmntinboxmsg': 'You will see announcement once you receive',
                    'anncmntinboxannmsg': 'Announcements',
                    'anncmntinboxseeall': 'See All',
                    'anncmntoutboxdelete': 'Delete',
                    'anncmntoutboxresend': 'Resend',
                    'anncmntttlresend': 'Resend Announcement',
                    'summary': 'Summary',
                    'readless': 'Read Less ...',
                    'readmore': '... Read More',
                    'location': 'Location',
                    'socialmedialinks': 'Social Media Links',
                    'showFilters': 'Show Filters',
                    'sortby': 'Sort by',
                    'contentCaps': 'CONTENT',
                    'authorCaps': 'AUTHOR',
                    'statusCaps': 'STATUS',
                    'pendingSince': 'Pending since',
                    'publisher': 'Publisher',
                    'year': 'Year',
                    'dashboardsevendaysfilter': 'LAST 7 DAYS',
                    'dashboardfourteendaysfilter': 'LAST 14 DAYS',
                    'dashboardfiveweeksfilter': 'LAST 5 WEEKS',
                    'dashboardfrombeginingfilter': 'FROM BEGINING',
                    'dashboardsortbystatus': 'Status',
                    'dashboardsortbyusername': 'User Name',
                    'dashboardsortbybatchend': 'Batch End On',
                    'dashboardsortbyorg': 'ORG',
                    'dashboardsortbyenrolledon': 'Enrolled On',
                    'dashboardnobatchselected': 'No batch selected!',
                    'dashboardnobatchselecteddesc': 'Please select a batch from the above list',
                    'dashboardnocourseselected': 'No course selected!',
                    'dashboardnocourseselecteddesc': 'Please select a course from the above list',
                    'creationdataset': 'Creation',
                    'consumptiondataset': 'Consumption',
                    'dashboardselectorg': 'Select Organization',
                    'dashboardnoorgselected': 'No organization selected!',
                    'dashboardnoorgselecteddesc': 'Please select a organization from the above list',
                    'countryCode': 'Country code',
                    'phoneVerfied': 'Phone verified',
                    'emailVerfied': 'Email verified',
                    'roles': 'Roles',
                    'position': 'Position',
                    'errorMessage': 'Error message',
                    'userID': 'UserId ',
                    'rootOrg': 'Root org ',
                    'regOrg': 'Registered org',
                    'orgId': 'OrgId',
                    'orgName': 'Org Name',
                    'isRootOrg': 'Is RootOrg',
                    'channel': 'Channel',
                    'externalId': 'External Id',
                    'homeUrl': 'Home Url',
                    'orgCode': 'Org Code',
                    'orgType': 'Org Type',
                    'preferredLanguage': 'Preferred Language',
                    'theme': 'Theme',
                    'createCourse': 'Create Course',
                    'enterOrgtype': 'Enter org type name',
                    'fileUploadDropAttachment': 'Drop relevant attachment here',
                    'fileUploadFormat': '(Format: .pdf, .png, .jpg. File Limit: 1MB)',
                    'fileUploadOr': 'or',
                    'fileUploadCancel': 'Cancel',
                    'certificationAward': 'Certifications & Awards',
                    'copycontent': 'Copying content...',
                    'markas': 'Mark as',
                    'badgeassignconfirmation': 'Are you sure you want to issue the badge to this content?',
                    'aboutthecourse': 'About the course',
                    'coursestructure': 'Course Structure',
                    'batchdetails': 'Batch Details',
                    'learners': 'Learners',
                    'mentors': 'Mentors',
                    'coursecreatedon': 'Course created on',
                    'updatedon': 'Updated on',
                    'selectorganization': 'Select Organization',
                    'mycourses': 'My Courses',
                    'lastlogin': 'Last login',
                    'lastlogintime': 'Last login time',
                    'showingresults': 'Showing results',
                    'in': 'in',
                    'selectorg': 'Select Org',
                    'ongoing': 'Ongoing',
                    'createbatch': 'Create Batch',
                    'batchdescription': 'DESCRIPTION OF BATCH',
                    'enrollcourse': 'ENROLL TO COURSE',
                    'batchmembers': 'MEMBERS OF BATCH',
                    'ongoingbatches': 'Ongoing Batches',
                    'batchof': 'Batch of ',
                    'createnewbatch': 'Create New Batch',
                    'inviteonly': 'Invite-only',
                    'open': 'Open',
                    'uploadattachment': 'UPLOAD ATTACHMENT',
                    'pdfcontents': 'Pdf contents',
                    'videos': 'Videos',
                    'imagecontents': 'Image Contents',
                    'htmlarchives': 'Html Archives',
                    'ecmlarchives': 'Ecml Archives',
                    'epubarchives': 'Epub Archives',
                    'h5parchives': 'H5p Archives',
                    'createfieldfilllater': 'These details can be filled when adding content to.',
                    'explore': 'Explore',
                    'first': 'First',
                    'previous': 'Previous',
                    'next': 'Next',
                    'last': 'Last',
                    'showingResultsFor': 'Showing results for \"{searchString}\"',
                    'enterQrCode': 'Enter DIAL code',
                    'exploreContentOn': 'Explore Content on {instance}',
                    'startExploringContent': 'Start exploring content by entering DIAL code',
                    'dialCodeDescription': 'DIAL Code is the 6 digit alphanumeric code found under a QR code in your text book',
                    'enterDialCode': 'Enter DIAL code here',
                    'dialCode': 'Dial code',
                    'linkedContents': 'Linked contents',
                    'publicFooterGetAccess': 'Get access to unlimited resources: worksheets, lesson plans and more!',
                    'downloadThe': 'Download the',
                    'app': 'App'
                },
                'scttl': {
                    'todo': 'To Do',
                    'myworkspace': 'My Workspace',
                    'contributions': 'Contributions',
                    'badges': 'Badges',
                    'instructions': 'Instructions :',
                    'blkuser': 'Block User',
                    'signup': 'Sign Up'
                },
                'tab': {
                    'home': 'Home',
                    'courses': 'Courses',
                    'resources': 'Library',
                    'community': 'Groups',
                    'profile': 'Profile'
                },
                'drpdn': {
                    'male': 'Male',
                    'female': 'Female',
                    'transgender': 'Transgender'
                },
                'prmpt': {
                    'enterphoneno': 'Enter 10 digit phone number',
                    'search': 'Search',
                    'curriculum': 'Curriculum',
                    'medium': 'Medium',
                    'subject': 'Subjects',
                    'grades': 'Grades',
                    'contenttypes': 'Content Types',
                    'concepts': 'Concepts',
                    'orgtype': 'Org Type',
                    'deletenote': 'Are you sure to delete this note?',
                    'userlocation': 'Location',
                    'roles': 'Roles',
                    'searchContent': 'Search content'
                },
                'intxt': {
                    't0001': 'Search for notes or title',
                    't0002': 'ADD YOUR COMMENT',
                    't0003': 'Select Batch To See Dashboard',
                    't0004': 'Search',
                    't0005': 'Select batch mentors',
                    't0006': 'Select batch members',
                    't0007': 'Update Batch Details',
                    't0008': 'Start searching by name',
                    't0009': 'Select User',
                    't0010': 'Select Course To See Dashboard',
                    't0011': 'Creation',
                    't0012': 'Consumption',
                    't0013': 'Grade',
                    't0014': 'Language'
                },
                'alt': {
                    'sortby': 'Sort ascending or descending order',
                    'filter': 'Filter'
                },
                'instn': {
                    't0001': 'You can add or upload details of up to 199 users at a time in one csv file',
                    't0002': 'You can add or upload details of up to 199 organizations at a time in one csv file',
                    't0003': '',
                    't0004': '',
                    't0005': '',
                    't0006': '',
                    't0007': 'The OrgName column is mandatory. Enter organization name in this column',
                    't0008': '',
                    't0009': '',
                    't0010': '',
                    't0011': 'You can track progress with process ID',
                    't0012': 'Please save the Process ID for your reference .You can track progress with process ID',
                    't0013': 'Download the csv file for reference',
                    't0014': 'CSV Columns:',
                    't0015': 'Upload Organizations',
                    't0016': 'Upload Users',
                    't0017': '',
                    't0018': 'Flag course as inappropriate',
                    't0019': 'Flag content as inappropriate',
                    't0020': 'Start typing to add a skill',
                    't0021': '',
                    't0022': 'Entering details in all other columns is optional:',
                    't0023': 'isRootOrg: Valid values for this column True False',
                    't0024': 'channel: Unique ID provided during master organization creation',
                    't0025': 'externalId: Unique ID associated with each organization in the administrating  organization’s repository',
                    't0026': 'provider: Channel ID of the administrator organization',
                    't0027': 'description: Details describing  the organization',
                    't0028': 'homeUrl: Organization’s homepage url',
                    't0029': 'orgCode: Organization’s unique code, if any,',
                    't0030': 'orgType: Type of organization, such as, NGO, primary school, secondary school etc',
                    't0031': 'preferredLanguage: Language preferences for the organization, if any',
                    't0032': '',
                    't0033': 'The following columns are mandatory:',
                    't0034': 'FirstName: The user’s first name',
                    't0035': 'Email: The user’s verified email ID',
                    't0036': '',
                    't0037': 'Password: Unique or common password given by organization',
                    't0038': 'All other columns are optional. These columns include information about the user such as:',
                    't0039': 'Phone',
                    't0040': '',
                    't0041': 'Grade: Classes taught by the user',
                    't0042': 'Location: User’s place of location of the user',
                    't0043': 'DOB: User’s date of birth, the value should be entered in DD-MM-YYYY format',
                    't0044': 'Gender: User’s gender',
                    't0045': '',
                    't0046': 'Profile summary: User’s profile summary',
                    't0047': '',
                    't0048': 'PhoneVerified: This key is required with value as true, if user provided phone value.',
                    't0049': 'channel is mandatory if value for column isRootorg is True',
                    't0050': 'externalid and provider are mutually mandatory',
                    't0051': 'Announcement type',
                    't0052': 'Please enter description for this announcement (Max: 1200 chars)',
                    't0053': 'Enter web url (starting with http or https)',
                    't0054': '',
                    't0055': 'Oops announcement details not found!',
                    't0056': 'Please try again..',
                    't0057': 'Please enter relevant title for this announcement (Max: 100 chars)',
                    't0058': 'Download this view as:',
                    't0059': 'CSV',
                    't0060': 'Thank you!',
                    't0061': 'Oops...',
                    't0062': '',
                    't0063': '',
                    't0064': 'Multiple addresses with same type selected. Please change any one.',
                    't0065': 'If user is not passing organisationId but passing OrgProvider, then user should pass OrgExternalId',
                    't0066': '',
                    't0067': '',
                },
                'snav': {
                    'start': 'Create',
                    'draft': 'Drafts',
                    'inreview': 'Review Submissions',
                    'published': 'Published',
                    'alluploads': 'All Uploads',
                    'upForReview': 'Up For Review',
                    'flagged': 'Flagged',
                    'limitedPublishing': 'Limited Publishing',
                    'allmycontents': 'All My Contents'
                },
                'pgttl': {
                    'takeanote': 'Take a note'
                },
                'lnk': {
                    'viewall': 'View All',
                    'profile': 'Profile',
                    'workSpace': 'Workspace',
                    'logout': 'Logout',
                    'dashboard': 'Admin dashboard',
                    'announcement': 'Announcement dashboard',
                    'myactivity': 'My Activity',
                    'coursebacthes': 'Course Batches',
                    'imglnkmsg': 'http://example.com/images/diagram.jpg optional title'
                }
            },
            'messages': {
                'stmsg': {
                    'm0001': 'We are fetching enrolled courses...',
                    'm0002': 'We are fetching data...',
                    'm0003': 'We are fetching course details...',
                    'm0004': 'Enrolling....',
                    'm0005': 'We are fetching data',
                    'm0006': 'No results found',
                    'm0007': 'Please search for something else.',
                    'm0008': 'no-results',
                    'm0009': 'Unable to play, please try again or close.',
                    'm0010': '',
                    'm0011': 'We are fetching draft content...',
                    'm0012': '',
                    'm0013': 'We are creating lesson...',
                    'm0014': 'We are creating book...',
                    'm0015': 'We are creating course...',
                    'm0016': 'We are creating collection...',
                    'm0017': 'We are uploading content...',
                    'm0018': 'We are fetching review content...',
                    'm0019': '',
                    'm0020': '',
                    'm0021': '',
                    'm0022': '',
                    'm0023': 'We are fetching uploaded content...',
                    'm0024': '',
                    'm0025': 'We are fetching content detail...',
                    'm0026': 'We are updating icon...',
                    'm0027': 'We are updating the content detail...',
                    'm0028': 'We are sending content for review...',
                    'm0029': 'We are publishing the content...',
                    'm0030': 'We are rejecting the content...',
                    'm0031': 'Invalid youtube url, Please check...',
                    'm0032': 'We are fetching up for review content...',
                    'm0033': '',
                    'm0034': 'We are deleting the content...',
                    'm0035': 'content not deleted',
                    'm0036': 'Please select content to',
                    'm0037': 'Please select action...',
                    'm0038': 'We are fetching flagged content...',
                    'm0039': '',
                    'm0040': 'We are accepting the flag...',
                    'm0041': 'We are discarding the flag...',
                    'm0042': 'Title is missing',
                    'm0043': 'Description is missing',
                    'm0044': 'Lesson type is missing',
                    'm0045': 'Audience is missing',
                    'm0046': 'Subject is missing',
                    'm0047': 'Grade is missing',
                    'm0048': 'Medium is missing',
                    'm0049': 'We are loading concept details...',
                    'm0050': 'We are creating lesson plan...',
                    'm0051': 'We are fetching enrolled courses...',
                    'm0052': 'We are fetching data...',
                    'm0053': 'We are fetching content...',
                    'm0054': 'We are creating note...',
                    'm0055': 'Fetching note detail, please wait...',
                    'm0056': 'We are removing note...',
                    'm0057': 'We are fetching notes...',
                    'm0058': '',
                    'm0059': 'We are updating note...',
                    'm0060': 'Strengthen your profile',
                    'm0061': 'Add more details now',
                    'm0062': 'Enter valid degree',
                    'm0063': 'Enter valid Address line 1',
                    'm0064': 'Enter City',
                    'm0065': 'Enter valid pin code',
                    'm0066': 'Enter First name',
                    'm0067': 'Please provide a valid phone number',
                    'm0068': 'Enter valid Email ID',
                    'm0069': 'Select language',
                    'm0070': 'Enter Instituition name',
                    'm0071': 'Enter Degree details',
                    'm0072': 'Enter valid Occupation / Work Title',
                    'm0073': 'Enter valid Organization',
                    'm0074': 'Loading profile ...',
                    'm0075': 'Updating profile ...',
                    'm0076': 'Fetching data for you....',
                    'm0077': 'We are submitting your request...',
                    'm0078': 'Uploading Organizations',
                    'm0079': 'Uploading users',
                    'm0080': 'Please upload file in csv formate only',
                    'm0081': 'No batches found',
                    'm0082': 'We are fetching limited published content...',
                    'm0083': '',
                    'm0084': 'Requesting sign up , please wait....',
                    'm0085': 'User name already exist, sign up with different username...',
                    'm0086': 'Email already exist, sign up with different email...',
                    'm0087': 'Please enter a valid user name, must have minimum 5 character',
                    'm0088': 'Please enter a valid password',
                    'm0089': 'Please enter a valid email',
                    'm0090': 'Please select languages',
                    'm0091': 'Please enter a valid phone number',
                    'm0092': 'Please enter a valid first name',
                    'm0093': 'Year of Passing is not formatted correctly',
                    'm0094': 'Enter valid percentage',
                    'm0095': '',
                    'm0096': 'Select Address Type',
                    'm0097': 'Enter valid city',
                    'm0098': 'Enter valid state',
                    'm0099': 'Enter valid country',
                    'm0100': 'Enter valid Address line 2',
                    'm0101': 'Please enter a valid url',
                    'm0102': 'is too large, maximum char size is 100',
                    'm0103': 'Enter valid designation',
                    'm0104': 'Enter valid grade',
                    'm0105': 'Title is required',
                    'm0106': 'Title is too long',
                    'm0107': 'From is required',
                    'm0108': 'Your Progress',
                    'm0109': 'Descripton is too long ',
                    'm0110': 'We are fetching all content...',
                    'm0111': 'Looks like there is nothing to show here. Please go to “Create” to start creating content',
                    'm0112': 'Content is coming soon',
                    'm0113': 'Enter valid startdate',
                    'm0114': 'Name is required '
                },
                'fmsg': {
                    'm0001': 'Fetching enrolled courses failed, please try again later...',
                    'm0002': 'Fetching other courses failed, please try again later...',
                    'm0003': 'Unable to get course schedule details.',
                    'm0004': 'Fetching data failed, please try again later...',
                    'm0005': 'Fetching profile failed, please try again later...',
                    'm0006': 'Fetching draft content failed, please try again later...',
                    'm0007': 'Creating lesson failed. Please login again to create lesson.',
                    'm0008': 'Creating book failed. Please login again to create book.',
                    'm0009': 'Creating course failed. Please login again to create course.',
                    'm0010': 'Creating collection failed. Please login again to create collection.',
                    'm0011': 'Uploading content failed. Please login again to create collection.',
                    'm0012': 'Fetching review content failed, please try again later...',
                    'm0013': 'Fetching published content failed, please try again later...',
                    'm0014': 'Fetching uploaded content failed, please try again later...',
                    'm0015': 'Fetching content detail failed, please try again later...',
                    'm0016': 'Updating icon failed, please try again later...',
                    'm0017': 'Updating content detail failed, please try again later...',
                    'm0018': 'Sending content for review failed, please try again later...',
                    'm0019': 'Publishing content failed, please try again later...',
                    'm0020': 'Rejecting content failed, please try again later...',
                    'm0021': 'Fetching up for review content failed, please try again later...',
                    'm0022': 'Deleting content failed, please try again later...',
                    'm0023': 'Fetching flagged content failed, please try again later...',
                    'm0024': 'Accepting flag failed, please try again later...',
                    'm0025': 'Discarding flag failed, please try again later...',
                    'm0026': 'Creating lesson plan failed. Please login again to create lesson plan.',
                    'm0027': 'Fetching enrolled courses failed, please try again later...',
                    'm0028': 'Fetching other courses failed, please try again later...',
                    'm0029': 'Fetching content failed, please try again later...',
                    'm0030': 'Creating note is failed, please try again later...',
                    'm0031': 'Fetching note detail is failed, please try again later...',
                    'm0032': 'Removing note is failed, please try again later...',
                    'm0033': 'Fetching note is failed, please try again later...',
                    'm0034': 'Updating note is failed, please try again later...',
                    'm0035': 'Profile image  update failed. Please try again later...',
                    'm0036': 'Description update failed. Please try again later..',
                    'm0037': 'Education update failed. Please try again later...',
                    'm0038': 'Experience update failed. Please try again later...',
                    'm0039': 'Basic information update failed. Please try again later...',
                    'm0040': 'Address update failed. Please try again later...',
                    'm0041': 'Education delete failed. Please try again later...',
                    'm0042': 'Experience delete failed. Please try again later...',
                    'm0043': 'Address delete failed. Please try again later...',
                    'm0044': 'Adding new education failed. Please try again later...',
                    'm0045': 'Adding new experience failed. Please try again later...',
                    'm0046': 'Adding new address failed. Please try again later...',
                    'm0047': 'Fetching profile failed, please try again later...',
                    'm0048': 'Updating user profile failed,please try again later...',
                    'm0049': 'Unable to load data.',
                    'm0050': 'Submitting request is failed, please try again later...',
                    'm0051': 'Something went wrong, please try again later...',
                    'm0052': 'Creating batch failed, please try again later...',
                    'm0053': 'Adding users to batch is failed, please try again later...',
                    'm0054': 'Fetching batch detail failed, please try again later...',
                    'm0055': 'Updating batch failed, please try again later...',
                    'm0056': 'Fetching users list failed, please try again later...',
                    'm0057': 'Fetching tenant details failed, please try again later...',
                    'm0058': 'Adding a new org type failed, please try again later',
                    'm0059': 'Fetching org type failed, please try again later',
                    'm0060': 'Org  type update failed, please try again later',
                    'm0061': 'Description update failed. Please try again later...',
                    'm0062': 'Adding new skill failed. Please try again later...',
                    'm0063': 'Skill endorsement failed, please try again later...',
                    'm0064': 'Fetching limited published content failed, please try again later...',
                    'm0065': 'Invalid content access',
                    'm0066': 'Content is not ready to play',
                    'm0067': 'Course is not ready to play',
                    'm0068': 'Profile update failed, please try again later ...',
                    'm0069': 'Fetching announcement types failed, please try again later...',
                    'm0070': 'Fetching announcement outbox list failed, please try again later...',
                    'm0071': 'Deleting announcement failed, please try again...',
                    'm0072': 'Fetching announcement inbox list failed, please try again later...',
                    'm0073': 'Unable to read announcement, please try again later...',
                    'm0074': 'Fetching announcement details failed, please try again later...',
                    'm0075': 'Fetching dashboard details failed, please try again later...',
                    'm0076': 'Please enter mandatory fields',
                    'm0077': 'Fetching search result failed..',
                    'm0078': 'Creating content failed. Please login again to create content.',
                    'm0079': 'Assigning badge failed, please try again later...',
                    'm0080': 'Fetching badge failed, please try again later...',
                    'm0081': 'Fetching all content failed, please try again later...',
                    'm0082': 'This course is not opened for enrolling'
                },
                'smsg': {
                    'm0001': 'success',
                    'm0002': 'Saved successfully...',
                    'm0003': 'Content sent for review...',
                    'm0004': 'Content published successfully...',
                    'm0005': 'Content rejected successfully...',
                    'm0006': 'Content deleted successfully...',
                    'm0007': 'Flag accepted successfully...',
                    'm0008': 'Flag discarded successfully...',
                    'm0009': 'Note created successfully...',
                    'm0010': 'Note detail fetched successfully...',
                    'm0011': 'Note deleted successfully...',
                    'm0012': 'Note detail fetched successfully...',
                    'm0013': 'Note updated successfully...',
                    'm0014': 'Education deleted successfully',
                    'm0015': 'Experience deleted successfully',
                    'm0016': 'Address deleted successfully',
                    'm0017': 'Profile successfully updated',
                    'm0018': 'Profile Image updated successfully',
                    'm0019': 'Description updated successfully',
                    'm0020': 'Education updated successfully',
                    'm0021': 'Experience updated successfully',
                    'm0022': 'Additional information  updated successfully',
                    'm0023': 'Address updated successfully',
                    'm0024': 'New education added successfully',
                    'm0025': 'New experience added successfully',
                    'm0026': 'New address added successfully',
                    'm0027': 'Request submitted successfully...',
                    'm0028': 'Roles updated successfully',
                    'm0029': 'User deleted successfully',
                    'm0030': 'Users uploaded successfully',
                    'm0031': 'Organizations uploaded successfully',
                    'm0032': 'Status fetched successfully',
                    'm0033': 'Batch created successfully...',
                    'm0034': 'Batch updated successfully...',
                    'm0035': 'Org type added successfully',
                    'm0036': 'Course Enrolled for this batch successfully...',
                    'm0037': 'updated successfully',
                    'm0038': 'New skill added successfully',
                    'm0039': 'Sign up successfully, Please login...',
                    'm0040': 'Profile field visibility updated successfully',
                    'moo41': 'Announcement cancelled successfully...',
                    'm0042': 'Content successfully copied',
                    'm0043': 'Endorsement successfull',
                    'm0044': 'Badge assigned successfully...'
                },
                'emsg': {
                    'm0001': 'Cannot enroll now.Try again later',
                    'm0002': 'error',
                    'm0003': 'You should enter Provider and External Id Or Organization Id',
                    'm0004': 'Cannot preview now.Try again later',
                    'm0005': 'Something went wrong, please try in some time....',
                    'm0006': 'Please select recipient(s)',
                    'm0007': 'size should be less than',
                    'm0008': 'Unable to copy content. Try again later'
                },
                'imsg': {
                    'm0001': 'This course is flagged as inappropriate and is currently under review.Please check again later.',
                    'm0002': 'info',
                    'm0003': 'warning',
                    'm0004': 'You are not authorized to access this resource',
                    'm0005': 'Please upload a valid image file. Supported file types: jpeg, jpg, png. Max size: 4MB.',
                    'm0006': 'is too large, maximum file size is',
                    'm0007': 'File accepted only pdf (Max size 25mb).',
                    'm0008': 'File accepted only mp4 (Max size 25mb).',
                    'm0009': 'File accepted only html zip (Max size 25mb).',
                    'm0010': 'File accepted only epub (Max size 25mb).',
                    'm0011': 'File accepted only h5p (Max size 25mb).',
                    'm0012': 'is not valid pdf file.',
                    'm0013': 'is not valid mp4 file.',
                    'm0014': 'is not valid zip file.',
                    'm0015': 'is not valid epub file.',
                    'm0016': 'is not valid h5p file.',
                    'm0017': 'Profile Completeness.',
                    'm0018': 'Content not found.',
                    'm0019': 'Course not found',
                    'm0020': 'location is removed sucessfully.',
                    'm0021': 'Please select recipient(s)',
                    'm0022': 'Stats for last 7 days',
                    'm0023': 'Stats for last 14 days',
                    'm0024': 'Stats for last 5 weeks',
                    'm0025': 'Stats from begining',
                    'm0026': 'Hi, this course is not available now. It is likely that the creator has made some changes to the course.',
                    'm0027': 'Hi, this content is not available now. It is likely that the creator has made some changes to the content.',
                    'm0028': 'No data found',
                    'm0029': 'No organization selected!',
                    'm0030': 'Addresses should not be of same type, please change any one.',
                    'm0031': 'You already have a current job, please mark one job as current job',
                    'm0032': 'Max upload size 4MB',
                    'm0033': '(Format: .pdf, .png, .jpg. File Limit: 1MB)',
                    'm0034': 'As the content is from an external source, it will be opened in a new tab.',
                    'm0035': 'Unauthorized access'
                }
            }
        }
    },
    cachedResourceData: {
        'value': {
            'messages': {
                'stmsg': {
                    'm0001': 'We are fetching enrolled courses...',
                    'm0002': 'We are fetching data...',
                    'm0003': 'We are fetching course details...',
                    'm0004': 'Enrolling....',
                    'm0005': 'We are fetching data',
                    'm0006': 'No results found',
                    'm0007': 'Please search for something else.',
                    'm0008': 'no-results',
                    'm0009': 'Unable to play, please try again or close.',
                    'm0010': '',
                    'm0011': 'We are fetching draft content...',
                    'm0012': '',
                    'm0013': 'We are creating lesson...',
                    'm0014': 'We are creating book...',
                    'm0015': 'We are creating course...',
                    'm0016': 'We are creating collection...',
                    'm0017': 'We are uploading content...',
                    'm0018': 'We are fetching review content...',
                    'm0019': '',
                    'm0020': '',
                    'm0021': 'We are fetching published content...',
                    'm0022': '',
                    'm0023': 'We are fetching uploaded content...',
                    'm0024': '',
                    'm0025': 'We are fetching content detail...',
                    'm0026': 'We are updating icon...',
                    'm0027': 'We are updating the content detail...',
                    'm0028': 'We are sending content for review...',
                    'm0029': 'We are publishing the content...',
                    'm0030': 'We are rejecting the content...',
                    'm0031': 'Invalid youtube url, Please check...',
                    'm0032': 'We are fetching up for review content...',
                    'm0033': '',
                    'm0034': 'We are deleting the content...',
                    'm0035': 'content not deleted',
                    'm0036': 'Please select content to',
                    'm0037': 'Please select action...',
                    'm0038': 'We are fetching flagged content...',
                    'm0039': '',
                    'm0040': 'We are accepting the flag...',
                    'm0041': 'We are discarding the flag...',
                    'm0042': 'Title is missing',
                    'm0043': 'Description is missing',
                    'm0044': 'Lesson type is missing',
                    'm0045': 'Audience is missing',
                    'm0046': 'Subject is missing',
                    'm0047': 'Grade is missing',
                    'm0048': 'Medium is missing',
                    'm0049': 'We are loading concept details...',
                    'm0050': 'We are creating lesson plan...',
                    'm0051': 'We are fetching enrolled courses...',
                    'm0052': 'We are fetching data...',
                    'm0053': 'We are fetching content...',
                    'm0054': 'We are creating note...',
                    'm0055': 'Fetching note detail, please wait...',
                    'm0056': 'We are removing note...',
                    'm0057': 'We are fetching notes...',
                    'm0058': '',
                    'm0059': 'We are updating note...',
                    'm0060': 'Strengthen your profile',
                    'm0061': 'Add more details now',
                    'm0062': 'Enter valid degree',
                    'm0063': 'Enter valid Address line 1',
                    'm0064': 'Enter City',
                    'm0065': 'Enter valid pin code',
                    'm0066': 'Enter First name',
                    'm0067': 'Please provide a valid phone number',
                    'm0068': 'Enter valid Email ID',
                    'm0069': 'Select language',
                    'm0070': 'Enter Instituition name',
                    'm0071': 'Enter Degree details',
                    'm0072': 'Enter valid Occupation / Work Title',
                    'm0073': 'Enter valid Organization',
                    'm0074': 'Loading profile ...',
                    'm0075': 'Updating profile ...',
                    'm0076': 'Fetching data for you....',
                    'm0077': 'We are submitting your request...',
                    'm0078': 'Uploading Organizations',
                    'm0079': 'Uploading users',
                    'm0080': 'Please upload file in csv formate only',
                    'm0081': 'No batches found',
                    'm0082': 'We are fetching limited published content...',
                    'm0083': '',
                    'm0084': 'Requesting sign up , please wait....',
                    'm0085': 'User name already exist, sign up with different username...',
                    'm0086': 'Email already exist, sign up with different email...',
                    'm0087': 'Please enter a valid user name, must have minimum 5 character',
                    'm0088': 'Please enter a valid password',
                    'm0089': 'Please enter a valid email',
                    'm0090': 'Please select languages',
                    'm0091': 'Please enter a valid phone number',
                    'm0092': 'Please enter a valid first name',
                    'm0093': 'Year of Passing is not formatted correctly',
                    'm0094': 'Enter valid percentage',
                    'm0095': '',
                    'm0096': 'Select Address Type',
                    'm0097': 'Enter valid city',
                    'm0098': 'Enter valid state',
                    'm0099': 'Enter valid country',
                    'm0100': 'Enter valid Address line 2',
                    'm0101': 'Please enter a valid url',
                    'm0102': 'is too large, maximum char size is 100',
                    'm0103': 'Enter valid designation',
                    'm0104': 'Enter valid grade',
                    'm0105': 'Title is required',
                    'm0106': 'Title is too long',
                    'm0107': 'From is required',
                    'm0108': 'Your Progress',
                    'm0109': 'Descripton is too long ',
                    'm0110': 'We are fetching all content...',
                    'm0111': 'Looks like there is nothing to show here. Please go to “Create” to start creating content',
                    'm0112': 'Content is coming soon',
                    'm0113': 'Enter valid startdate',
                    'm0114': 'Name is required '
                },
                'fmsg': {
                    'm0001': 'Fetching enrolled courses failed, please try again later...',
                    'm0002': 'Fetching other courses failed, please try again later...',
                    'm0003': 'Unable to get course schedule details.',
                    'm0004': 'Fetching data failed, please try again later...',
                    'm0005': 'Fetching profile failed, please try again later...',
                    'm0006': 'Fetching draft content failed, please try again later...',
                    'm0007': 'Creating lesson failed. Please login again to create lesson.',
                    'm0008': 'Creating book failed. Please login again to create book.',
                    'm0009': 'Creating course failed. Please login again to create course.',
                    'm0010': 'Creating collection failed. Please login again to create collection.',
                    'm0011': 'Uploading content failed. Please login again to create collection.',
                    'm0012': 'Fetching review content failed, please try again later...',
                    'm0013': 'Fetching published content failed, please try again later...',
                    'm0014': 'Fetching uploaded content failed, please try again later...',
                    'm0015': 'Fetching content detail failed, please try again later...',
                    'm0016': 'Updating icon failed, please try again later...',
                    'm0017': 'Updating content detail failed, please try again later...',
                    'm0018': 'Sending content for review failed, please try again later...',
                    'm0019': 'Publishing content failed, please try again later...',
                    'm0020': 'Rejecting content failed, please try again later...',
                    'm0021': 'Fetching up for review content failed, please try again later...',
                    'm0022': 'Deleting content failed, please try again later...',
                    'm0023': 'Fetching flagged content failed, please try again later...',
                    'm0024': 'Accepting flag failed, please try again later...',
                    'm0025': 'Discarding flag failed, please try again later...',
                    'm0026': 'Creating lesson plan failed. Please login again to create lesson plan.',
                    'm0027': 'Fetching enrolled courses failed, please try again later...',
                    'm0028': 'Fetching other courses failed, please try again later...',
                    'm0029': 'Fetching content failed, please try again later...',
                    'm0030': 'Creating note is failed, please try again later...',
                    'm0031': 'Fetching note detail is failed, please try again later...',
                    'm0032': 'Removing note is failed, please try again later...',
                    'm0033': 'Fetching note is failed, please try again later...',
                    'm0034': 'Updating note is failed, please try again later...',
                    'm0035': 'Profile image  update failed. Please try again later...',
                    'm0036': 'Description update failed. Please try again later..',
                    'm0037': 'Education update failed. Please try again later...',
                    'm0038': 'Experience update failed. Please try again later...',
                    'm0039': 'Basic information update failed. Please try again later...',
                    'm0040': 'Address update failed. Please try again later...',
                    'm0041': 'Education delete failed. Please try again later...',
                    'm0042': 'Experience delete failed. Please try again later...',
                    'm0043': 'Address delete failed. Please try again later...',
                    'm0044': 'Adding new education failed. Please try again later...',
                    'm0045': 'Adding new experience failed. Please try again later...',
                    'm0046': 'Adding new address failed. Please try again later...',
                    'm0047': 'Fetching profile failed, please try again later...',
                    'm0048': 'Updating user profile failed,please try again later...',
                    'm0049': 'Unable to load data.',
                    'm0050': 'Submitting request is failed, please try again later...',
                    'm0051': 'Something went wrong, please try again later...',
                    'm0052': 'Creating batch failed, please try again later...',
                    'm0053': 'Adding users to batch is failed, please try again later...',
                    'm0054': 'Fetching batch detail failed, please try again later...',
                    'm0055': 'Updating batch failed, please try again later...',
                    'm0056': 'Fetching users list failed, please try again later...',
                    'm0057': 'Fetching tenant details failed, please try again later...',
                    'm0058': 'Adding a new org type failed, please try again later',
                    'm0059': 'Fetching org type failed, please try again later',
                    'm0060': 'Org  type update failed, please try again later',
                    'm0061': 'Description update failed. Please try again later...',
                    'm0062': 'Adding new skill failed. Please try again later...',
                    'm0063': 'Skill endorsement failed, please try again later...',
                    'm0064': 'Fetching limited published content failed, please try again later...',
                    'm0065': 'Invalid content access',
                    'm0066': 'Content is not ready to play',
                    'm0067': 'Course is not ready to play',
                    'm0068': 'Profile update failed, please try again later ...',
                    'm0069': 'Fetching announcement types failed, please try again later...',
                    'm0070': 'Fetching announcement outbox list failed, please try again later...',
                    'm0071': 'Deleting announcement failed, please try again...',
                    'm0072': 'Fetching announcement inbox list failed, please try again later...',
                    'm0073': 'Unable to read announcement, please try again later...',
                    'm0074': 'Fetching announcement details failed, please try again later...',
                    'm0075': 'Fetching dashboard details failed, please try again later...',
                    'm0076': 'Please enter mandatory fields',
                    'm0077': 'Fetching search result failed..',
                    'm0078': 'Creating content failed. Please login again to create content.',
                    'm0079': 'Assigning badge failed, please try again later...',
                    'm0080': 'Fetching badge failed, please try again later...',
                    'm0081': 'Fetching all content failed, please try again later...',
                    'm0082': 'This course is not opened for enrolling'
                },
                'smsg': {
                    'm0001': 'success',
                    'm0002': 'Saved successfully...',
                    'm0003': 'Content sent for review...',
                    'm0004': 'Content published successfully...',
                    'm0005': 'Content rejected successfully...',
                    'm0006': 'Content deleted successfully...',
                    'm0007': 'Flag accepted successfully...',
                    'm0008': 'Flag discarded successfully...',
                    'm0009': 'Note created successfully...',
                    'm0010': 'Note detail fetched successfully...',
                    'm0011': 'Note deleted successfully...',
                    'm0012': 'Note detail fetched successfully...',
                    'm0013': 'Note updated successfully...',
                    'm0014': 'Education deleted successfully',
                    'm0015': 'Experience deleted successfully',
                    'm0016': 'Address deleted successfully',
                    'm0017': 'Profile successfully updated',
                    'm0018': 'Profile Image updated successfully',
                    'm0019': 'Description updated successfully',
                    'm0020': 'Education updated successfully',
                    'm0021': 'Experience updated successfully',
                    'm0022': 'Additional information  updated successfully',
                    'm0023': 'Address updated successfully',
                    'm0024': 'New education added successfully',
                    'm0025': 'New experience added successfully',
                    'm0026': 'New address added successfully',
                    'm0027': 'Request submitted successfully...',
                    'm0028': 'Roles updated successfully',
                    'm0029': 'User deleted successfully',
                    'm0030': 'Users uploaded successfully',
                    'm0031': 'Organizations uploaded successfully',
                    'm0032': 'Status fetched successfully',
                    'm0033': 'Batch created successfully...',
                    'm0034': 'Batch updated successfully...',
                    'm0035': 'Org type added successfully',
                    'm0036': 'Course Enrolled for this batch successfully...',
                    'm0037': 'updated successfully',
                    'm0038': 'New skill added successfully',
                    'm0039': 'Sign up successfully, Please login...',
                    'm0040': 'Profile field visibility updated successfully',
                    'moo41': 'Announcement cancelled successfully...',
                    'm0042': 'Content successfully copied',
                    'm0043': 'Endorsement successfull',
                    'm0044': 'Badge assigned successfully...'
                },
                'emsg': {
                    'm0001': 'Cannot enroll now.Try again later',
                    'm0002': 'error',
                    'm0003': 'You should enter Provider and External Id Or Organization Id',
                    'm0004': 'Cannot preview now.Try again later',
                    'm0005': 'Something went wrong, please try in some time....',
                    'm0006': 'Please select recipient(s)',
                    'm0007': 'size should be less than',
                    'm0008': 'Unable to copy content. Try again later'
                },
                'imsg': {
                    'm0001': 'This course is flagged as inappropriate and is currently under review.Please check again later.',
                    'm0002': 'info',
                    'm0003': 'warning',
                    'm0004': 'You are not authorized to access this resource',
                    'm0005': 'Please upload a valid image file. Supported file types: jpeg, jpg, png. Max size: 4MB.',
                    'm0006': 'is too large, maximum file size is',
                    'm0007': 'File accepted only pdf (Max size 25mb).',
                    'm0008': 'File accepted only mp4 (Max size 25mb).',
                    'm0009': 'File accepted only html zip (Max size 25mb).',
                    'm0010': 'File accepted only epub (Max size 25mb).',
                    'm0011': 'File accepted only h5p (Max size 25mb).',
                    'm0012': 'is not valid pdf file.',
                    'm0013': 'is not valid mp4 file.',
                    'm0014': 'is not valid zip file.',
                    'm0015': 'is not valid epub file.',
                    'm0016': 'is not valid h5p file.',
                    'm0017': 'Profile Completeness.',
                    'm0018': 'Content not found.',
                    'm0019': 'Course not found',
                    'm0020': 'location is removed sucessfully.',
                    'm0021': 'Please select recipient(s)',
                    'm0022': 'Stats for last 7 days',
                    'm0023': 'Stats for last 14 days',
                    'm0024': 'Stats for last 5 weeks',
                    'm0025': 'Stats from begining',
                    'm0026': 'Hi, this course is not available now. It is likely that the creator has made some changes to the course.',
                    'm0027': 'Hi, this content is not available now. It is likely that the creator has made some changes to the content.',
                    'm0028': 'No data found',
                    'm0029': 'No organization selected!',
                    'm0030': 'Addresses should not be of same type, please change any one.',
                    'm0031': 'You already have a current job, please mark one job as current job',
                    'm0032': 'Max upload size 4MB',
                    'm0033': '(Format: .pdf, .png, .jpg. File Limit: 1MB)',
                    'm0034': 'As the content is from an external source, it will be opened in a new tab.',
                    'm0035': 'Unauthorized access'
                }
            },
            'frmelmnts': {
                'btn': {
                    'add': 'ADD',
                    'yes': 'YES',
                    'no': 'NO',
                    'ok': 'OK',
                    'cancel': 'CANCEL',
                    'save': 'SAVE',
                    'resume': 'RESUME',
                    'update': 'UPDATE',
                    'clear': 'CLEAR',
                    'publish': 'PUBLISH',
                    'reject': 'REJECT',
                    'tryagain': 'TRY AGAIN',
                    'close': 'CLOSE',
                    'accept': 'ACCEPT',
                    'discard': 'DISCARD',
                    'startcreating': 'START CREATING',
                    'tcyes': 'Yes',
                    'requestChanges': 'REQUEST CHANGES',
                    'tcno': 'No',
                    'edit': 'EDIT',
                    'submit': 'SUBMIT',
                    'download': 'DOWNLOAD',
                    'apply': 'APPLY',
                    'reset': 'RESET',
                    'smplcsv': 'DOWNLOAD SAMPLE CSV',
                    'uploadorgscsv': 'UPLOAD ORGANIZATIONS CSV',
                    'uploadusrscsv': 'UPLOAD USERS CSV',
                    'chksts': 'CHECK STATUS',
                    'approve': 'APPROVE',
                    'tcok': 'Ok',
                    'viewless': 'VIEW LESS',
                    'viewmore': 'VIEW MORE',
                    'finish': 'FINISH',
                    'signup': 'SIGN UP',
                    'login': 'LOGIN',
                    'back': 'BACK',
                    'anncmntgotit': 'GOT IT',
                    'anncmntconfirmrecipients': 'CONFIRM RECIPIENTS',
                    'anncmntpreview': 'PREVIEW ANNOUNCEMENT',
                    'anncmntsendanncmnt': 'SEND ANNOUNCEMENT',
                    'anncmntselectrecipients': 'SELECT RECIPIENTS',
                    'anncmnteditrecipients': 'EDIT RECIPIENTS',
                    'anncmntdtlsview': 'VIEW',
                    'yesiamsure': 'YES, IM SURE\t',
                    'enroll': 'Enroll\t',
                    'create': 'CREATE\t',
                    'copylink': 'COPY LINK\t',
                    'first': 'FIRST\t',
                    'previous': 'PREVIOUS\t',
                    'next': 'NEXT\t',
                    'last': 'LAST\t',
                    'resumecourse': 'RESUME COURSE\t',
                    'viewcoursestats': 'VIEW COURSE STATS'
                },
                'bdge': {
                    'course': 'Course'
                },
                'lbl': {
                    'tcyes': 'Yes',
                    'tcno': 'No',
                    'tcfrom': 'From',
                    'tcto': 'To',
                    'title': 'Title',
                    'description': 'Description',
                    'takenote': 'TAKE NOTE',
                    'addnote': 'ADD NOTE',
                    'mynotebook': 'My Notebook',
                    'mynotes': 'My Notes',
                    'search': 'Search',
                    'edit': 'Edit',
                    'delete': 'Delete',
                    'deletenote': 'Delete Note',
                    'yes': 'YES',
                    'no': 'NO',
                    'batches': 'Batches',
                    'insertimage': 'Insert Image',
                    'textbook': 'Book',
                    'textbookdescription': 'Build books using resources for an interesting learning experience.',
                    'course': 'Course',
                    'coursedescription': '',
                    'lesson': 'Resource',
                    'lessondescription': '',
                    'collection': 'Collection',
                    'collectiondescription': 'Compile resources of your choice.',
                    'lessonplandescription': 'Frame lesson plans with structured sections for an efficient learning experience.',
                    'lessonplan': 'Lesson Plan',
                    'contentupload': 'Upload Content',
                    'contentuploaddescription': 'You can upload content here.',
                    'createlessontext': 'Create Resource',
                    'name': 'Name',
                    'lessonfillater': 'These details can be filled when adding content to Resource.',
                    'createcollection': 'Create Collection',
                    'collectionfillater': 'These details can be filled when adding content to Collection.',
                    'createtextbook': 'Create Book',
                    'bookfillater': 'These details can be filled when adding content to Book.',
                    'createlessonplan': 'Create Lesson Plan',
                    'lpfilllater': 'These details can be filled when adding content to Lesson Plan.',
                    'designcourse': 'Design Course',
                    'coursefilllater': 'These details can be filled when adding content to Course.',
                    'author': 'Author',
                    'medium': 'Medium',
                    'class': 'Class',
                    'credits': 'Credits',
                    'subject': 'Subject',
                    'lastupdate': 'Last update',
                    'createdon': 'Created On',
                    'status': 'Status',
                    'flaggedreason': 'Flagged reason',
                    'flaggedby': 'Flagged by',
                    'flaggeddescription': 'Flagged Description',
                    'contentinformation': 'Content Information',
                    'concept': 'Concepts',
                    'curriculum': 'Curriculum',
                    'keywords': 'Keywords',
                    'agreeandproceedtext': 'All content created and uploaded here will be licensed under CC-BY 4.0.',
                    'deletecontent': 'Delete Content',
                    'deleteconfirm': 'Are you sure to delete this content?',
                    'deletepublishedcontent': 'Retire Content',
                    'deletepublishedconfirm': 'Retire myself from the content?',
                    'viewworkspace': 'View your workspace',
                    'resourcetype': 'Resource Type',
                    'experience': 'Experience',
                    'worktitle': 'Occupation / Work Title',
                    'designation': 'Designation',
                    'organization': 'Organization',
                    'subjectstaught': 'Subject(s) taught',
                    'iscurrentjob': 'Is this your current job',
                    'address': 'Address',
                    'seladdresstype': 'Select Address Type',
                    'permanent': 'Permanent',
                    'current': 'Current',
                    'addressline1': 'Address Line 1',
                    'addressline2': 'Address Line 2',
                    'city': 'City',
                    'state': 'State',
                    'country': 'Country',
                    'pincode': 'Pin Code',
                    'education': 'Education',
                    'degree': 'Degree',
                    'yop': 'Year of Passing',
                    'institute': 'Institution Name',
                    'grade': 'Grade',
                    'percentage': 'Percentage',
                    'board': 'Board/University',
                    'addlInfo': 'Additional Information',
                    'email': 'Email ID',
                    'phone': 'Phone number',
                    'gender': 'Gender',
                    'language': 'Language(s) known',
                    'birthdate': 'Birthdate (dd/mm/yyyy)',
                    'subjects': 'Subjects of expertise',
                    'contents': 'Contents',
                    'currentlocation': 'Current location',
                    'grades': 'Grades',
                    'socialmedia': 'Social media',
                    'facebook': 'Facebook',
                    'twitter': 'Twitter',
                    'linkedIn': 'LinkedIn',
                    'blog': 'Blog',
                    'whatwentwrong': 'What went wrong?',
                    'whatwentwrongdesc': '',
                    'contentname': 'CONTENT NAME',
                    'selectreason': 'SELECT A REASON',
                    'share': 'Share',
                    'sharelink': 'Share by the link -',
                    'batchname': 'NAME OF BATCH',
                    'aboutbatch': 'ABOUT THIS BATCH',
                    'startdate': 'START DATE',
                    'enddate': 'END DATE',
                    'natureofbatch': 'BATCH TYPE',
                    'bacthmembers': 'MEMBERS IN THE BATCH',
                    'batchmentors': 'MENTORS IN THE BATCH',
                    'batchparticipants': 'SELECTED PARTICIPANTS',
                    'batchselmentors': 'SELECTED MENTORS',
                    'inactive': 'Inactive',
                    'active': 'Active',
                    'blocked': 'Blocked',
                    'retired': 'Retired',
                    'filters': 'Filters',
                    'filterby': 'Filter by',
                    'sort': 'Sort',
                    'chkuploadsts': 'Check Upload Status',
                    'upldfile': 'Uploaded File',
                    'processid': 'Process ID',
                    'provider': 'OrgProvider',
                    'extlid': 'OrgExternalId',
                    'orgid': 'OrgId',
                    'successres': 'Success Results',
                    'failres': 'Failure Results',
                    'confmblk': 'Are you sure to Block',
                    'selrole': 'Select Role',
                    'org': 'Org',
                    'assgnbdge': 'Assign Badge',
                    'cnfmassgn': 'Do you want to assign',
                    'orgtypes': 'Organization Type',
                    'addorgtype': 'Add Organization Type',
                    'updateorgtype': 'Update Organization Type',
                    'confirmblock': 'Are you sure to Block',
                    'confirmassign': 'Do you want to assign',
                    'jobProfile': 'Experience',
                    'avatar': 'Profile picture',
                    'profileSummary': 'Profile description',
                    'firstName': 'First name',
                    'lastName': 'Last name',
                    'skillTags': 'Skill Tags',
                    'addSkills': 'Add Skills',
                    'username': 'User Name',
                    'password': 'Password',
                    'phonenumber': 'Phone Number',
                    'dob': 'Date Of Birth',
                    'lang': 'Language',
                    'languages': 'Bengali,English,Gujarati,Hindi,Kannada,Marathi,Punjabi,Tamil,Telugu',
                    'page': 'Page',
                    'tryagain': 'Try Again',
                    'close': 'Close',
                    'createnewanncmnt': 'Create New Announcement',
                    'createnewanncmntdesc': 'Fill in all the required fields to create the announcement.',
                    'resendanncmntdesc': 'You can make any edits required and resend the announcement.',
                    'selectrecipient': 'Select Announcement Recipients',
                    'selectrecipientdesc': 'Select locations who should receive the announcement.',
                    'editrecipientdesc': 'Edit locations who should receive the announcement.',
                    'confirmrecipient': 'Confirm Announcement Recipients',
                    'confirmrecipientdesc': 'Review and confirm your announcement recipients.',
                    'previewanncmnt': 'Preview Announcement',
                    'previewanncmntdesc': 'This is how your announcement will look.',
                    'anncmntstep': 'STEP',
                    'anncmnttitle': 'TITLE',
                    'anncmntfrom': 'FROM',
                    'anncmntfromDesc': 'Please enter organisation/department that has sent the announcement',
                    'anncmnttype': 'ANNOUNCEMENT TYPE',
                    'anncmntdesc': 'DESCRIPTION (OPTIONAL)',
                    'anncmntlink': 'URL / WEBLINK',
                    'anncmntaddlink': 'Add URL/weblink',
                    'anncmntaddlinkdesc': '(For example, you can link a Google Form)',
                    'anncmntaddmorelink': 'Add Another URL/weblink',
                    'anncmntuploadfile': 'UPLOAD ATTACHMENT',
                    'anncmntsentsuccess': 'Announcement Sent!',
                    'anncmntsentdesc': '',
                    'anncmntdtlsweblinks': 'Weblinks',
                    'anncmntdtlsattachments': 'Attachments',
                    'anncmntdtlssenton': 'Sent on',
                    'anncmntcancel': 'Are you sure you want to stop creating this announcement',
                    'anncmntcanceldesc': 'You will lose your work if you close this announcement',
                    'anncmntresentmsg': 'Announcement Resent',
                    'anncmntresentmsgdesc': 'Your announcement has been resent to all the choosen recipients.',
                    'anncmntall': 'All Announcements',
                    'anncmntmine': 'My Announcements',
                    'anncmntreadmore': '... Read More',
                    'anncmntcreate': 'CREATE ANNOUNCEMENT',
                    'anncmntsent': 'Showing all sent announcements',
                    'anncmntnotfound': 'No announcement found!',
                    'anncmntplzcreate': 'Please create announcement',
                    'anncmntlastupdate': 'Consumption data last updated on',
                    'anncmntcancelconfirm': 'Are you sure you want to stop showing this announcement?',
                    'anncmntcancelconfirmdescrption': 'Users will not be able to see this announcement after this action.',
                    'anncmnttblname': 'Name',
                    'anncmnttblpublished': 'Published',
                    'anncmnttblsent': 'Sent',
                    'anncmnttblreceived': 'Received',
                    'anncmnttblseen': 'Seen',
                    'anncmnttblactions': 'Actions',
                    'anncmntinboxmsg': 'You will see announcement once you receive',
                    'anncmntinboxannmsg': 'Announcements',
                    'anncmntinboxseeall': 'See All',
                    'anncmntoutboxdelete': 'Delete',
                    'anncmntoutboxresend': 'Resend',
                    'anncmntttlresend': 'Resend Announcement',
                    'summary': 'Summary',
                    'readless': 'Read Less ...',
                    'readmore': '... Read More',
                    'location': 'Location',
                    'socialmedialinks': 'Social Media Links',
                    'showFilters': 'Show Filters',
                    'sortby': 'Sort by',
                    'contentCaps': 'CONTENT',
                    'authorCaps': 'AUTHOR',
                    'statusCaps': 'STATUS',
                    'pendingSince': 'Pending since',
                    'publisher': 'Publisher',
                    'year': 'Year',
                    'dashboardsevendaysfilter': 'LAST 7 DAYS',
                    'dashboardfourteendaysfilter': 'LAST 14 DAYS',
                    'dashboardfiveweeksfilter': 'LAST 5 WEEKS',
                    'dashboardfrombeginingfilter': 'FROM BEGINING',
                    'dashboardsortbystatus': 'Status',
                    'dashboardsortbyusername': 'User Name',
                    'dashboardsortbybatchend': 'Batch End On',
                    'dashboardsortbyorg': 'ORG',
                    'dashboardsortbyenrolledon': 'Enrolled On',
                    'dashboardnobatchselected': 'No batch selected!',
                    'dashboardnobatchselecteddesc': 'Please select a batch from the above list',
                    'dashboardnocourseselected': 'No course selected!',
                    'dashboardnocourseselecteddesc': 'Please select a course from the above list',
                    'creationdataset': 'Creation',
                    'consumptiondataset': 'Consumption',
                    'dashboardselectorg': 'Select Organization',
                    'dashboardnoorgselected': 'No organization selected!',
                    'dashboardnoorgselecteddesc': 'Please select a organization from the above list',
                    'countryCode': 'Country code',
                    'phoneVerfied': 'Phone verified',
                    'emailVerfied': 'Email verified',
                    'roles': 'Roles',
                    'position': 'Position',
                    'errorMessage': 'Error message',
                    'userID': 'UserId ',
                    'rootOrg': 'Root org ',
                    'regOrg': 'Registered org',
                    'orgId': 'OrgId',
                    'orgName': 'Org Name',
                    'isRootOrg': 'Is RootOrg',
                    'channel': 'Channel',
                    'externalId': 'External Id',
                    'homeUrl': 'Home Url',
                    'orgCode': 'Org Code',
                    'orgType': 'Org Type',
                    'preferredLanguage': 'Preferred Language',
                    'theme': 'Theme',
                    'createCourse': 'Create Course',
                    'enterOrgtype': 'Enter org type name',
                    'fileUploadDropAttachment': 'Drop relevant attachment here',
                    'fileUploadFormat': '(Format: .pdf, .png, .jpg. File Limit: 1MB)',
                    'fileUploadOr': 'or',
                    'fileUploadCancel': 'Cancel',
                    'certificationAward': 'Certifications & Awards',
                    'copycontent': 'Copying content...',
                    'markas': 'Mark as',
                    'badgeassignconfirmation': 'Are you sure you want to issue the badge to this content?',
                    'aboutthecourse': 'About the course',
                    'coursestructure': 'Course Structure',
                    'batchdetails': 'Batch Details',
                    'learners': 'Learners',
                    'mentors': 'Mentors',
                    'coursecreatedon': 'Course created on',
                    'updatedon': 'Updated on',
                    'selectorganization': 'Select Organization',
                    'mycourses': 'My Courses',
                    'lastlogin': 'Last login',
                    'lastlogintime': 'Last login time',
                    'showingresults': 'Showing results',
                    'in': 'in',
                    'selectorg': 'Select Org',
                    'ongoing': 'Ongoing',
                    'createbatch': 'Create Batch',
                    'batchdescription': 'DESCRIPTION OF BATCH',
                    'enrollcourse': 'ENROLL TO COURSE',
                    'batchmembers': 'MEMBERS OF BATCH',
                    'ongoingbatches': 'Ongoing Batches',
                    'batchof': 'Batch of ',
                    'createnewbatch': 'Create New Batch',
                    'inviteonly': 'Invite-only',
                    'open': 'Open',
                    'uploadattachment': 'UPLOAD ATTACHMENT',
                    'pdfcontents': 'Pdf contents',
                    'videos': 'Videos',
                    'imagecontents': 'Image Contents',
                    'htmlarchives': 'Html Archives',
                    'ecmlarchives': 'Ecml Archives',
                    'epubarchives': 'Epub Archives',
                    'h5parchives': 'H5p Archives',
                    'createfieldfilllater': 'These details can be filled when adding content to.',
                    'explore': 'Explore',
                    'first': 'First',
                    'previous': 'Previous',
                    'next': 'Next',
                    'last': 'Last',
                    'showingResultsFor': 'Showing results for \"{searchString}\"',
                    'enterQrCode': 'Enter DIAL code',
                    'exploreContentOn': 'Explore Content on {instance}',
                    'startExploringContent': 'Start exploring content by entering DIAL code',
                    'dialCodeDescription': 'DIAL Code is the 6 digit alphanumeric code found under a QR code in your text book',
                    'enterDialCode': 'Enter DIAL code here',
                    'dialCode': 'Dial code',
                    'linkedContents': 'Linked contents',
                    'publicFooterGetAccess': 'Get access to unlimited resources: worksheets, lesson plans and more!',
                    'downloadThe': 'Download the',
                    'app': 'App'
                },
                'scttl': {
                    'todo': 'To Do',
                    'myworkspace': 'My Workspace',
                    'contributions': 'Contributions',
                    'badges': 'Badges',
                    'instructions': 'Instructions :',
                    'blkuser': 'Block User',
                    'signup': 'Sign Up'
                },
                'tab': {
                    'home': 'Home',
                    'courses': 'Courses',
                    'resources': 'Library',
                    'community': 'Groups',
                    'profile': 'Profile'
                },
                'drpdn': {
                    'male': 'Male',
                    'female': 'Female',
                    'transgender': 'Transgender'
                },
                'prmpt': {
                    'enterphoneno': 'Enter 10 digit phone number',
                    'search': 'Search',
                    'curriculum': 'Curriculum',
                    'medium': 'Medium',
                    'subject': 'Subjects',
                    'grades': 'Grades',
                    'contenttypes': 'Content Types',
                    'concepts': 'Concepts',
                    'orgtype': 'Org Type',
                    'deletenote': 'Are you sure to delete this note?',
                    'userlocation': 'Location',
                    'roles': 'Roles',
                    'searchContent': 'Search content'
                },
                'intxt': {
                    't0001': 'Search for notes or title',
                    't0002': 'ADD YOUR COMMENT',
                    't0003': 'Select Batch To See Dashboard',
                    't0004': 'Search',
                    't0005': 'Select batch mentors',
                    't0006': 'Select batch members',
                    't0007': 'Update Batch Details',
                    't0008': 'Start searching by name',
                    't0009': 'Select User',
                    't0010': 'Select Course To See Dashboard',
                    't0011': 'Creation',
                    't0012': 'Consumption',
                    't0013': 'Grade',
                    't0014': 'Language'
                },
                'alt': {
                    'sortby': 'Sort ascending or descending order',
                    'filter': 'Filter'
                },
                'instn': {
                    't0001': 'You can add or upload details of up to 199 users at a time in one csv file',
                    't0002': 'You can add or upload details of up to 199 organizations at a time in one csv file',
                    't0003': '',
                    't0004': '',
                    't0005': '',
                    't0006': '',
                    't0007': 'The OrgName column is mandatory. Enter organization name in this column',
                    't0008': '',
                    't0009': '',
                    't0010': '',
                    't0011': 'You can track progress with process ID',
                    't0012': 'Please save the Process ID for your reference .You can track progress with process ID',
                    't0013': 'Download the csv file for reference',
                    't0014': 'CSV Columns:',
                    't0015': 'Upload Organizations',
                    't0016': 'Upload Users',
                    't0017': '',
                    't0018': 'Flag course as inappropriate',
                    't0019': 'Flag content as inappropriate',
                    't0020': 'Start typing to add a skill',
                    't0021': '',
                    't0022': 'Entering details in all other columns is optional:',
                    't0023': 'isRootOrg: Valid values for this column True False',
                    't0024': 'channel: Unique ID provided during master organization creation',
                    't0025': 'externalId: Unique ID associated with each organization in the administrating  organization’s repository',
                    't0026': 'provider: Channel ID of the administrator organization',
                    't0027': 'description: Details describing  the organization',
                    't0028': 'homeUrl: Organization’s homepage url',
                    't0029': 'orgCode: Organization’s unique code, if any,',
                    't0030': 'orgType: Type of organization, such as, NGO, primary school, secondary school etc',
                    't0031': 'preferredLanguage: Language preferences for the organization, if any',
                    't0032': '',
                    't0033': 'The following columns are mandatory:',
                    't0034': 'FirstName: The user’s first name',
                    't0035': 'Email: The user’s verified email ID',
                    't0036': '',
                    't0037': 'Password: Unique or common password given by organization',
                    't0038': 'All other columns are optional. These columns include information about the user such as:',
                    't0039': 'Phone',
                    't0040': '',
                    't0041': 'Grade: Classes taught by the user',
                    't0042': 'Location: User’s place of location of the user',
                    't0043': 'DOB: User’s date of birth, the value should be entered in DD-MM-YYYY format',
                    't0044': 'Gender: User’s gender',
                    't0045': '',
                    't0046': 'Profile summary: User’s profile summary',
                    't0047': '',
                    't0048': 'PhoneVerified: This key is required with value as true, if user provided phone value.',
                    't0049': 'channel is mandatory if value for column isRootorg is True',
                    't0050': 'externalid and provider are mutually mandatory',
                    't0051': 'Announcement type',
                    't0052': 'Please enter description for this announcement (Max: 1200 chars)',
                    't0053': 'Enter web url (starting with http or https)',
                    't0054': '',
                    't0055': 'Oops announcement details not found!',
                    't0056': 'Please try again..',
                    't0057': 'Please enter relevant title for this announcement (Max: 100 chars)',
                    't0058': 'Download this view as:',
                    't0059': 'CSV',
                    't0060': 'Thank you!',
                    't0061': 'Oops...',
                    't0062': '',
                    't0063': '',
                    't0064': 'Multiple addresses with same type selected. Please change any one.',
                    't0065': 'If user is not passing organisationId but passing OrgProvider, then user should pass OrgExternalId',
                    't0066': '',
                    't0067': ''
                },
                'snav': {
                    'start': 'Create',
                    'draft': 'Drafts',
                    'inreview': 'Review Submissions',
                    'published': 'Published',
                    'alluploads': 'All Uploads',
                    'upForReview': 'Up For Review',
                    'flagged': 'Flagged',
                    'limitedPublishing': 'Limited Publishing',
                    'allmycontents': 'All My Contents'
                },
                'pgttl': {
                    'takeanote': 'Take a note'
                },
                'lnk': {
                    'viewall': 'View All',
                    'profile': 'Profile',
                    'workSpace': 'Workspace',
                    'logout': 'Logout',
                    'dashboard': 'Admin dashboard',
                    'announcement': 'Announcement dashboard',
                    'myactivity': 'My Activity',
                    'coursebacthes': 'Course Batches',
                    'imglnkmsg': 'http://example.com/images/diagram.jpg optional title'
                }
            }
        },
        'options': {
            'expires': 1530167319922,
            'maxAge': 600
        }
    }
};
