import { ActivatedRoute, Router } from '@angular/router';
import { OnInit } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { GlobalService } from '../../services/global.service';
import { UciService } from '../../services/uci.service';
import * as i0 from "@angular/core";
export declare class ConversationAddComponent implements OnInit {
    private uciService;
    private router;
    private activatedRoute;
    private fb;
    private globalService;
    verifyAllModal: any;
    currentViewState: string;
    stepIndex: number;
    selectedLogic: any[];
    userSegments: any[];
    column: string;
    sortDirection: string;
    reverse: boolean;
    collectionListModal: boolean;
    isLoaderShow: boolean;
    isModalLoaderShow: boolean;
    logicFormRequest: {};
    isCheckedTermCondition: boolean;
    conversationForm: UntypedFormGroup;
    logicForm: UntypedFormGroup;
    termsAndConditionModal: boolean;
    verifyAllItemsModal: boolean;
    conversationId: any;
    selectedLogicIndex: any;
    startMinDate: Date;
    endMinDate: any;
    Appropriateness: {
        text: string;
        checks: boolean;
    }[];
    contentDetails: {
        text: string;
        checks: boolean;
    }[];
    usability: {
        text: string;
        checks: boolean;
    }[];
    isSubmit: boolean;
    odkFileAlreadyExist: boolean;
    isStartingMessageExist: boolean;
    fileErrorStatus: any;
    user: any;
    constructor(uciService: UciService, router: Router, activatedRoute: ActivatedRoute, fb: UntypedFormBuilder, globalService: GlobalService);
    ngOnInit(): void;
    userSegment(): void;
    onUserSegmentCancel(): void;
    onUserSegmentAddClick(): void;
    onUserSegmentAdd(segments: any): void;
    onUserSegmentCreate(segment: any): void;
    onUserSegmentDelete(index: any): void;
    nextStep(): void;
    backToStepOne(): void;
    onAddCancel(): void;
    onSubmit(isTriggerBot?: boolean): void;
    startConversation(bot: any): void;
    closeVerifyModal(): void;
    openModel(): void;
    openTermAndConditionModel(): void;
    openItemsVerifyModal(isSubmitBtn: boolean): void;
    onLogicAdd(): void;
    getEditLogicData(item: any, index: any): void;
    onFileUpload(event: any): void;
    onDelete(logic: any, index: any): void;
    getUserSegmentDetail(): void;
    allCheck(isAllCheck?: boolean): void;
    onStarringMessageChange(): void;
    manualDownload(): void;
    sampleODKDownload(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ConversationAddComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ConversationAddComponent, "lib-conversation-add", never, {}, {}, never, never, false, never>;
}
//# sourceMappingURL=conversation-add.component.d.ts.map