export const Response = {
    successData: {
        'id': 'api.user.read',
        'ver': 'v1',
        'ts': '2018-04-18 13:23:23:081+0000',
        'params': {
            'resmsgid': null,
            'msgid': '1ec7b22d-347e-7050-bec3-24c4660584ae',
            'err': null,
            'status': 'success',
            'errmsg': null
        },
        'responseCode': 'OK',
        'result': {
            'response': {
                'lastName': 'Kumar',
                'webPages': [],
                'tcStatus': null,
                'education': [
                    {
                        'updatedBy': null,
                        'address': {
                            'country': null,
                            'updatedBy': null,
                            'city': 'Bangalore1',
                            'updatedDate': null,
                            'userId': null,
                            'zipcode': '560135',
                            'addType': null,
                            'createdDate': '2017-09-20 05:28:03:526+0000',
                            'isDeleted': null,
                            'createdBy': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                            'addressLine1': '2121 winding hill dr',
                            'addressLine2': 'Frazer town1',
                            'id': '0123362151343226882',
                            'state': 'Karnataka1'
                        },
                        'yearOfPassing': 2012,
                        'degree': 'Bachelor of Science',
                        'updatedDate': null,
                        'userId': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                        'addressId': '0123362151343226882',
                        'duration': null,
                        'courseName': null,
                        'createdDate': '2017-09-20 05:28:03:543+0000',
                        'isDeleted': null,
                        'createdBy': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                        'boardOrUniversity': 'Anna University',
                        'grade': 'B',
                        'percentage': 72.5,
                        'name': 'MG College',
                        'id': '0123362151441121281'
                    },
                    {
                        'updatedBy': null,
                        'address': {
                            'country': null,
                            'updatedBy': null,
                            'city': 'Bangalore1',
                            'updatedDate': null,
                            'userId': null,
                            'zipcode': '560135',
                            'addType': null,
                            'createdDate': '2017-09-20 05:28:03:552+0000',
                            'isDeleted': null,
                            'createdBy': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                            'addressLine1': '2121 winding hill dr',
                            'addressLine2': 'Frazer town1',
                            'id': '0123362130441584644',
                            'state': 'Karnataka1'
                        },
                        'yearOfPassing': 2009,
                        'degree': 'Plus 2',
                        'updatedDate': null,
                        'userId': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                        'addressId': '0123362130441584644',
                        'duration': null,
                        'courseName': null,
                        'createdDate': '2017-09-20 05:28:03:560+0000',
                        'isDeleted': null,
                        'createdBy': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                        'boardOrUniversity': 'CBSE',
                        'grade': null,
                        'percentage': null,
                        'name': 'Delhi Public School',
                        'id': '0123362175063736323'
                    }
                ],
                'gender': 'male',
                'regOrgId': null,
                'subject': [
                    'Physics',
                    'Math',
                    'English'
                ],
                'roles': [
                    'COURSE_MENTOR',
                    'CONTENT_CREATOR',
                    'PUBLIC'
                ],
                'language': [],
                'updatedDate': null,
                'skills': [],
                'isDeleted': null,
                'organisations': [],
                'provider': null,
                'countryCode': '+91',
                'id': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                'tempPassword': null,
                'email': 'co***********@ilimi.in',
                'rootOrg': {
                    'dateTime': null,
                    'preferredLanguage': 'English',
                    'approvedBy': null,
                    'channel': 'ROOT_ORG',
                    'description': 'Andhra State Boardsssssss',
                    'updatedDate': '2018-03-28 09:43:09:345+0000',
                    'addressId': null,
                    'orgType': null,
                    'provider': null,
                    'orgCode': 'sunbird',
                    'theme': null,
                    'id': 'ORG_001',
                    'communityId': null,
                    'isApproved': null,
                    'slug': 'sunbird',
                    'identifier': 'ORG_001',
                    'thumbnail': null,
                    'orgName': 'Sunbird',
                    'updatedBy': '781c21fc-5054-4ee0-9a02-fbb1006a4fdd',
                    'address': {
                        'country': 'India',
                        'zipCode': '560035',
                        'createdDate': '2017-07-12 03:46:11:112+0530',
                        'updatedBy': '781c21fc-5054-4ee0-9a02-fbb1006a4fdd',
                        'city': 'bangalore',
                        'createdBy': '7d086e8c-68ac-4aaa-8b91-d75ff922bae5',
                        'state': 'Karnataka',
                        'id': '01247011624949350416'
                    },
                    'externalId': null,
                    'isRootOrg': true,
                    'rootOrgId': 'abc',
                    'approvedDate': null,
                    'imgUrl': null,
                    'homeUrl': null,
                    'isDefault': null,
                    'contactDetail': [],
                    'createdDate': null,
                    'createdBy': null,
                    'parentOrgId': null,
                    'hashTagId': 'b00bc992ef25f1a9a8d63291e20efc8d',
                    'noOfMembers': 1,
                    'status': null
                },
                'identifier': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                'thumbnail': null,
                'address': [],
                'jobProfile': [
                    {
                        'jobName': 'jobName1',
                        'orgName': 'AP ORG',
                        'role': 'teacher',
                        'updatedBy': null,
                        'address': {
                            'country': null,
                            'updatedBy': null,
                            'city': 'Bangalore1',
                            'updatedDate': null,
                            'userId': null,
                            'zipcode': '560135',
                            'addType': null,
                            'createdDate': '2017-09-20 05:28:03:578+0000',
                            'isDeleted': null,
                            'createdBy': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                            'addressLine1': '2121 winding hill dr',
                            'addressLine2': 'Frazer town1',
                            'id': '0123362195486064648',
                            'state': 'Karnataka1'
                        },
                        'endDate': '1992-10-12',
                        'isVerified': null,
                        'subject': [
                            'Physics',
                            'Chemistry'
                        ],
                        'joiningDate': '1992-10-12',
                        'updatedDate': null,
                        'isCurrentJob': null,
                        'verifiedBy': null,
                        'userId': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                        'boardName': null,
                        'orgId': '123',
                        'addressId': '0123362195486064648',
                        'createdDate': '2017-09-20 05:28:03:584+0000',
                        'isDeleted': null,
                        'createdBy': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                        'verifiedDate': null,
                        'isRejected': null,
                        'id': '0123362135457710087'
                    },
                    {
                        'jobName': 'jobName',
                        'orgName': 'AP ORG',
                        'role': 'teacher',
                        'updatedBy': null,
                        'address': {
                            'country': null,
                            'updatedBy': null,
                            'city': 'Bangalore1',
                            'updatedDate': null,
                            'userId': null,
                            'zipcode': '560135',
                            'addType': null,
                            'createdDate': '2017-09-20 05:28:03:568+0000',
                            'isDeleted': null,
                            'createdBy': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                            'addressLine1': '2121 winding hill dr',
                            'addressLine2': 'Frazer town1',
                            'id': '0123362153007267846',
                            'state': 'Karnataka1'
                        },
                        'endDate': '1992-10-12',
                        'isVerified': null,
                        'subject': [
                            'Physics',
                            'Chemistry'
                        ],
                        'joiningDate': '1992-10-12',
                        'updatedDate': null,
                        'isCurrentJob': null,
                        'verifiedBy': null,
                        'userId': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                        'boardName': null,
                        'orgId': '123',
                        'addressId': '0123362153007267846',
                        'createdDate': '2017-09-20 05:28:03:572+0000',
                        'isDeleted': null,
                        'createdBy': 'c7e35899-2ed1-47ad-9338-b1d8e2170483',
                        'verifiedDate': null,
                        'isRejected': null,
                        'id': '0123362137688883205'
                    }
                ],
                'profileSummary': null,
                'tcUpdatedDate': null,
                'avatar': null,
                'rootOrgId': 'ORG_001',
                'badges': [],
                'emailVerified': null,
                'firstName': 'Amit',
                'lastLoginTime': null,
                'createdDate': '2017-09-20 05:28:03:506+0000',
                'createdBy': null,
                'phone': null,
                'dob': '1992-10-12',
                'grade': [],
                'currentLoginTime': null,
                'location': null,
                'status': 1
            }
        }
    }
};
