sonar.projectKey=SunbirdEd-portal
sonar.organization=sunbird-ed

sonar.sources=src
sonar.tests=src/app/client/src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/assets/**,**/thirdparty/**
sonar.coverage.exclusions=**/*.spec.ts,**/*.mock.data.ts,**/*.spec.data.ts

sonar.javascript.lcov.reportPaths=src/app/client/coverage/lcov.info
