const { defaults } = require('jest-config');
const { pathsToModuleNameMapper } = require('ts-jest');
const { compilerOptions } = require('./tsconfig.json');

module.exports = {
  name: 'sunbird-portal',
  preset: "jest-preset-angular",
  "verbose": true,
  "testEnvironment": "jsdom",
  roots: [
    "<rootDir>"
  ],
  setupFilesAfterEnv: [
    "<rootDir>/setup-jest.ts"
  ],
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, { prefix: '<rootDir>/src' }),
  // "modulePaths": [
  //   "<rootDir>",
  // ],
  // preset is optional, you don't need it in case you use babel preset typescript
  preset: 'ts-jest',
  // note this prefix option
  moduleFileExtensions: [...defaults.moduleFileExtensions, 'ts', 'tsx'],
  transformIgnorePatterns: [
    "<rootDir>/node_modules/"
  ],
  testPathIgnorePatterns: [
    "/node_modules/",
    ".data.spec.ts",
    ".spec.data.ts",
    "sb-form-location-selection.delegate.spec.ts",
    "src/app/modules/badging/services/content-badge.service.spec.ts",
    "src/app/modules/certificate/models/cert-config-model/cert-config-model.spec.ts",
    "src/app/modules/certificate/services/upload-certificate/upload-certificate.service.spec.ts",
    "src/app/modules/content-search/services/content-search/content-search.service.spec.ts",
    "src/app/modules/core/guard/auth-gard.service.spec.ts",
    "src/app/modules/core/services/action/action.service.spec.ts",
    "src/app/modules/core/services/app-update/app-update.service.spec.ts",
    "src/app/modules/core/services/badges/badges.service.spec.ts",
    "src/app/modules/core/services/cert-reg/cert-reg.service.spec.ts",
    "src/app/modules/core/services/certificate/certificate.service.spec.ts",
    "src/app/modules/core/services/channel/channel.service.spec.ts",
    "src/app/modules/core/services/cloud/cloud.service.spec.ts",
    "src/app/modules/core/services/content/content.service.spec.ts",
    "src/app/modules/core/services/copy-content/copy-content.service.spec.ts",
    "src/app/modules/core/services/course/course.service.spec.ts",
    "src/app/modules/core/services/data/data.service.spec.ts",
    "src/app/modules/core/services/device/device.service.spec.ts",
    "src/app/modules/core/services/device-register/device-register.service.spec.ts",
    "src/app/modules/core/services/dhiti/dhiti.service.spec.ts",
    "src/app/modules/core/services/electron/electron.service.spec.ts",
    "src/app/modules/core/services/ext-plugin/ext-plugin.service.spec.ts",
    "src/app/modules/core/services/form/form.service.spec.ts",
    "src/app/modules/core/services/framework/framework.service.spec.ts",
    "src/app/modules/core/services/generalisedLable/generaliseLable.service.spec.ts",
    "src/app/modules/core/services/kendra/kendra.service.spec.ts",
    "src/app/modules/core/services/learner/learner.service.spec.ts",
    "src/app/modules/core/services/managed-user/managed-user.service.spec.ts",
    "src/app/modules/core/services/observation/observation.service.spec.ts",
    "src/app/modules/core/services/observation-util/observation-util.service.spec.ts",
    "src/app/modules/core/services/org-details/org-details.service.spec.ts",
    "src/app/modules/core/services/otp/otp.service.spec.ts",
    "src/app/modules/core/services/page-api/page-api.service.spec.ts",
    "src/app/modules/core/services/permission/permission.service.spec.ts",
    "src/app/modules/core/services/player/player.service.spec.ts",
    "src/app/modules/core/services/public-data/public-data.service.spec.ts",
    "src/app/modules/core/services/report/report.service.spec.ts",
    "src/app/modules/core/services/schema/schema.service.spec.ts",
    "src/app/modules/core/services/search/search.service.spec.ts",
    "src/app/modules/core/services/segmentation-tag/segmentation-tag.service.spec.ts",
    "src/app/modules/core/services/tenant/tenant.service.spec.ts",
    "src/app/modules/core/services/tnc/tnc.service.spec.ts",
    "src/app/modules/core/services/user/user.service.spec.ts",
    "src/app/modules/dashboard/components/data-chart/data-chart.component.spec.ts",
    "src/app/modules/dashboard/components/dataset/dataset.component.spec.ts",
    "src/app/modules/dashboard/components/list-all-reports/list-all-reports.component.spec.ts",
    "src/app/modules/dashboard/components/re-issue-certificate/re-issue-certificate.component.spec.ts",
    "src/app/modules/dashboard/services/chartjs/line-chart/line-chart.service.spec.ts",
    "src/app/modules/dashboard/services/course-consumption/course-consumption.service.spec.ts",
    "src/app/modules/dashboard/services/course-progress/course-progress.service.spec.ts",
    "src/app/modules/dashboard/services/dashboard-utils/dashboard-utils.service.spec.ts",
    "src/app/modules/dashboard/services/dataset/dataset.service.spec.ts",
    "src/app/modules/dashboard/services/download/download.service.spec.ts",
    "src/app/modules/dashboard/services/organization/organization.service.spec.ts",
    "src/app/modules/dashboard/services/renderer/renderer.service.spec.ts",
    "src/app/modules/dashboard/services/report/report.service.spec.ts",
    "src/app/modules/dashboard/services/usage/usage.service.spec.ts",
    "src/app/modules/dial-code-search/components/dial-code/dial-code.component.spec.ts",
    "src/app/modules/dial-code-search/components/dial-code-card/dial-code-card.component.spec.ts",
    "src/app/modules/dial-code-search/services/dial-code/dial-code.service.spec.ts",
    "src/app/modules/discussion/components/forum/forum.component.spec.ts",
    "src/app/modules/discussion/services/discussion/discussion.service.spec.ts",
    "src/app/modules/explore-page/components/explore-page/explore-page.component.spec.ts",
    "src/app/modules/groups/components/activity/activity-dashboard/activity-dashboard.component.spec.ts",
    "src/app/modules/groups/components/activity/activity-list/activity-list.component.spec.ts",
    "src/app/modules/groups/components/activity/activity-search/activity-search.component.spec.ts",
    "src/app/modules/groups/components/activity/add-activity-content-types/add-activity-content-types.component.spec.ts",
    "src/app/modules/groups/components/add-member/add-member.component.spec.ts",
    "src/app/modules/groups/components/ftu-popup/ftu-popup.component.spec.ts",
    "src/app/modules/groups/components/group-details/group-details.component.spec.ts",
    "src/app/modules/groups/components/group-header/group-header.component.spec.ts",
    "src/app/modules/groups/components/group-members/group-members.component.spec.ts",
    "src/app/modules/groups/components/my-groups/my-groups.component.spec.ts",
    "src/app/modules/groups/services/groups/groups.service.spec.ts",
    "src/app/modules/learn/components/batch/update-course-batch/update-course-batch.component.spec.ts",
    "src/app/modules/learn/components/course-consumption/certificate-name-update-popup/certificate-name-update-popup.component.spec.ts",
    "src/app/modules/learn/components/course-consumption/course-completion/course-completion.component.spec.ts",
    "src/app/modules/learn/components/course-consumption/course-consumption-header/course-consumption-header.component.spec.ts",
    "src/app/modules/learn/components/course-consumption/course-details/course-details.component.spec.ts",
    "src/app/modules/learn/services/assessment/assessment-score.service.spec.ts",
    "src/app/modules/learn/services/course-batch/course-batch.service.spec.ts",
    "src/app/modules/learn/services/course-consumption/course-consumption.service.spec.ts",
    "src/app/modules/learn/services/courseProgress/course-progress.service.spec.ts",
    "src/app/modules/manage/components/user-org-management/user-org-management.component.spec.ts",
    "src/app/modules/manage/services/manage/manage.service.spec.ts",
    "src/app/modules/notification/components/in-app-notification/in-app-notification.component.spec.ts",
    "src/app/modules/notification/services/group-notification-wrapper/group-notification-wrapper.service.spec.ts",
    "src/app/modules/notification/services/notification/notification-service-impl.spec.ts",
    "src/app/modules/observation/components/add-entity/add-entity.component.spec.ts",
    "src/app/modules/observation/components/observation-details/observation-details.component.spec.ts",
    "src/app/modules/observation/components/observation-listing/observation-listing.component.spec.ts",
    "src/app/modules/observation/guards/ml/ml.guard.spec.ts",
    "src/app/modules/org-management/services/org-management/org-management.service.spec.ts",
    "src/app/modules/org-management/services/org-type/org-type.service.spec.ts",
    "src/app/modules/player-helper/components/content-player/content-player.component.spec.ts",
    "src/app/modules/player-helper/components/content-rating/content-rating.component.spec.ts",
    "src/app/modules/player-helper/components/contentplayer-page/contentplayer-page.component.spec.ts",
    "src/app/modules/player-helper/components/player/player.component.spec.ts",
    "src/app/modules/player-helper/service/quml-player/quml-player.service.spec.ts",
    "src/app/modules/public/module/help/components/offline-help-videos/offline-help-videos.component.spec.ts",
    "src/app/modules/public/module/help/services/faq/faq.service.spec.ts",
    "src/app/modules/public/module/offline/components/about-us/about-us.component.spec.ts",
    "src/app/modules/public/module/offline/components/content-manager/content-manager.component.spec.ts",
    "src/app/modules/public/module/offline/components/content-manager-info-pop-up/content-manager-info-pop-up.component.spec.ts",
    "src/app/modules/public/module/offline/components/info-card/info-card.component.spec.ts",
    "src/app/modules/public/module/offline/components/load-content/load-content.component.spec.ts",
    "src/app/modules/public/module/offline/components/telemetry/telemetry.component.spec.ts",
    "src/app/modules/public/module/offline/components/telemetry-import/telemetry-import.component.spec.ts",
    "src/app/modules/public/module/offline/services/content-manager/content-manager.service.spec.ts",
    "src/app/modules/public/module/offline/services/electron-dialog/electron-dialog.service.spec.ts",
    "src/app/modules/public/module/offline/services/offline-report-issues/offline-report-issues.service.spec.ts",
    "src/app/modules/public/module/offline/services/system-info/system-info.service.spec.ts",
    "src/app/modules/public/module/offline/services/telemetry-actions/telemetry-actions.service.spec.ts",
    "src/app/modules/public/module/sign-in/sso/components/update-contact/update-contact.component.spec.ts",
    "src/app/modules/public/module/signup/services/signup/signup.service.spec.ts",
    "src/app/modules/public/services/public-player/public-player.service.spec.ts",
    "src/app/modules/questionnaire/questionnaire.service.spec.ts",
    "src/app/modules/questionnaire/guard/can-deactivate.guard.spec.ts",
    "src/app/modules/questionnaire/questionnaire/questionnaire.component.spec.ts",
    "src/app/modules/recover-account/components/identify-account/identify-account.component.spec.ts",
    "src/app/modules/recover-account/components/select-account-identifier/select-account-identifier.component.spec.ts",
    "src/app/modules/recover-account/components/verify-account-identifier/verify-account-identifier.component.spec.ts",
    "src/app/modules/recover-account/services/recover-account/recover-account.service.spec.ts",
    "src/app/modules/report/components/all-evidence/all-evidence.component.spec.ts",
    "src/app/modules/report/components/entity-list/entity-list.component.spec.ts",
    "src/app/modules/report/components/report-view/report-view.component.spec.ts",
    "src/app/modules/search/services/user-search/user-search.service.spec.ts",
    "src/app/modules/shared/components/alert-modal/alert-modal.component.spec.ts",
    "src/app/modules/shared/components/batch-card/batch-card.component.spec.ts",
    "src/app/modules/shared/components/card/card.component.spec.ts",
    "src/app/modules/shared/components/card-creation/card-creation.component.spec.ts",
    "src/app/modules/shared/components/desktop-app-update/desktop-app-update.component.spec.ts",
    "src/app/modules/shared/components/load-offline-content/load-offline-content.component.spec.ts",
    "src/app/modules/shared/components/material-auto-complete/material-auto-complete.component.spec.ts",
    "src/app/modules/shared/components/offline-application-download/offline-application-download.component.spec.ts",
    "src/app/modules/shared/components/on-demand-reports/on-demand-reports.component.spec.ts",
    "src/app/modules/shared/components/qr-code-modal/qr-code-modal.component.spec.ts",
    "src/app/modules/shared/components/sb-datatable/sb-datatable.component.spec.ts",
    "src/app/modules/shared/components/select-option-group/select-option-group.component.spec.ts",
    "src/app/modules/shared/components/system-warning/system-warning.component.spec.ts",
    "src/app/modules/shared/directives/add-to-group/add-to-group.directive.spec.ts",
    "src/app/modules/shared/directives/highlight-text/highlight-text.directive.spec.ts",
    "src/app/modules/shared/directives/telemetry-events/telemetry-events.directive.spec.ts",
    "src/app/modules/shared/services/activity-dashboard/activity-dashboard.service.spec.ts",
    "src/app/modules/shared/services/browser-cache-ttl/browser-cache-ttl.service.spec.ts",
    "src/app/modules/shared/services/config/config.service.spec.ts",
    "src/app/modules/shared/services/connection-service/connection.service.spec.ts",
    "src/app/modules/shared/services/content-utils/content-utils.service.spec.ts",
    "src/app/modules/shared/services/discussion-telemetry/discussion-telemetry.service.spec.ts",
    "src/app/modules/shared/services/exturl-util/exturl-util.service.spec.ts",
    "src/app/modules/shared/services/layoutconfig/layout.service.spec.ts",
    "src/app/modules/shared/services/navigate/router-navigation.service.spec.ts",
    "src/app/modules/shared/services/navigation-helper/navigation-helper.service.spec.ts",
    "src/app/modules/shared/services/offline-card-service/offline-card.service.spec.ts",
    "src/app/modules/shared/services/on-demand-report/on-demand-report.service.spec.ts",
    "src/app/modules/shared/services/recaptcha/recaptcha.service.spec.ts",
    "src/app/modules/shared/services/resource/resource.service.spec.ts",
    "src/app/modules/shared/services/util/util.service.spec.ts",
    "src/app/modules/shared/services/window-scroll/window-scroll.service.spec.ts",
    "src/app/modules/shared-feature/components/batch-info/batch-info.component.spec.ts",
    "src/app/modules/shared-feature/components/cert-preview-popup/cert-preview-popup.component.spec.ts",
    "src/app/modules/shared-feature/components/confirmation-popup/confirmation-popup.component.spec.ts",
    "src/app/modules/shared-feature/components/dashboard/dashboard.component.spec.ts",
    "src/app/modules/shared-feature/components/onboarding-user-selection/onboarding-user-selection.component.spec.ts",
    "src/app/modules/shared-feature/components/tnc-popup/terms-conditions-popup.component.spec.ts",
    "src/app/modules/telemetry/directives/telemetry-interact/telemetry-interact.directive.spec.ts",
    "src/app/modules/telemetry/services/telemetry/telemetry.service.spec.ts",
    "src/app/modules/workspace/components/all-content/all-content.component.spec.ts",
    "src/app/modules/workspace/components/all-textbooks/all-textbooks.component.spec.ts",
    "src/app/modules/workspace/components/batch-page-section/batch-page-section.component.spec.ts",
    "src/app/modules/workspace/components/collaborating-on/collaborating-on.component.spec.ts",
    "src/app/modules/workspace/components/data-driven/data-driven.component.spec.ts",
    "src/app/modules/workspace/components/draft/draft.component.spec.ts",
    "src/app/modules/workspace/components/limited-published/limited-published.component.spec.ts",
    "src/app/modules/workspace/components/published/published.component.spec.ts",
    "src/app/modules/workspace/components/request-changes-popup/request-changes-popup.component.spec.ts",
    "src/app/modules/workspace/services/batch/batch.service.spec.ts",
    "src/app/modules/workspace/services/editors/editor.service.spec.ts",
    "src/app/modules/workspace/services/review-comments/review-comments.service.spec.ts",
    "src/app/modules/workspace/services/work-space/workspace.service.spec.ts",
    "src/app/plugins/location/components/delegate/sb-form-location-selection.delegate.spec.ts",
    "src/app/plugins/location/services/location/location.service.spec.ts",
    "src/app/plugins/profile/components/profile-page/profile-page.component.spec.ts",
    "src/app/plugins/profile/components/submit-teacher-details/submit-teacher-details.component.spec.ts",
    "src/app/plugins/profile/components/update-contact-details/update-contact-details.component.spec.ts",
    "src/app/plugins/profile/services/profile/profile.service.spec.ts",
    "src/app/service/popup-control.service.spec.ts",
    "src/app/service/CsLibInitializer/cs-lib-initializer.service.spec.ts",
    "src/app/service/LazzyLoadScript/lazzy-load-script.service.spec.ts",
    "src/app/modules/telemetry/directives/"
  ]
  // transform: {
  //   "lodash-es": "<rootDir>/node_modules/lodash-es"
  // }
}

function setModuleNameMapper() {
  console.log('_______________MODULE_MAPPER________________')
  let _moduleMaps = pathsToModuleNameMapper(compilerOptions.paths, { prefix: '<rootDir>/src' });
  console.log(_moduleMaps); // TODO: log!
  console.log('_______________MODULE_MAPPER________________')
  // return _moduleMaps;
}
setModuleNameMapper()