import { SuiModule } from 'ng2-semantic-ui/dist';
import { SlickModule } from 'ngx-slick';
import { FormsModule } from '@angular/forms';
import {
  AnnouncementInboxCardComponent,
  PageSectionComponent,
  NoResultComponent,
  AppLoaderComponent,
  PlayerComponent,
  CollectionTreeComponent,
  FancyTreeComponent,
  CardComponent,
  ShareLinkComponent,
  CollectionPlayerMetadataComponent,
  BrowserCompatibilityComponent,
  QrCodeModalComponent,
  RedirectComponent,
  CustomMultiSelectComponent
} from './components';
import {
  ConfigService,
  ResourceService,
  FileUploadService,
  ToasterService,
  WindowScrollService,
  BrowserCacheTtlService,
  PaginationService,
  RouterNavigationService,
  NavigationHelperService,
  UtilService,
  ContentUtilsServiceService,
  ExternalUrlPreviewService,
  PlayContent
} from './services';
import { CommonModule } from '@angular/common';
import { NgModule, ModuleWithProviders } from '@angular/core';
import {
  DateFormatPipe,
  DateFilterXtimeAgoPipe,
  FilterPipe,
  InterpolatePipe
} from './pipes';
import { Ng2IzitoastService } from 'ng2-izitoast';
import { CacheService } from 'ng2-cache-service';
import { DeviceDetectorModule } from 'ngx-device-detector';
import { DeviceDetectorService } from 'ngx-device-detector';
import { TelemetryModule } from '@sunbird/telemetry';
import { NgInviewModule } from 'angular-inport';
import { CdnprefixPipe } from './pipes/cdnprefix.pipe';
import {
  MatAutocompleteModule,
  MatBadgeModule,
  MatBottomSheetModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCheckboxModule,
  MatChipsModule,
  MatDatepickerModule,
  MatDialogModule,
  MatDividerModule,
  MatExpansionModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatNativeDateModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatProgressSpinnerModule,
  MatRadioModule,
  MatRippleModule,
  MatSelectModule,
  MatSidenavModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatSnackBarModule,
  MatSortModule,
  MatStepperModule,
  MatTableModule,
  MatTabsModule,
  MatToolbarModule,
  MatTooltipModule,
  MatTreeModule,
  MatCardModule
} from '@angular/material';
@NgModule({
  imports: [
    CommonModule,
    SuiModule,
    SlickModule,
    FormsModule,
    TelemetryModule,
    NgInviewModule,
    MatAutocompleteModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatTreeModule,
    MatCardModule
  ],
  providers: [PlayContent],
  declarations: [
    AppLoaderComponent,
    AnnouncementInboxCardComponent,
    DateFormatPipe,
    PageSectionComponent,
    NoResultComponent,
    DateFilterXtimeAgoPipe,
    CollectionTreeComponent,
    FancyTreeComponent,
    PlayerComponent,
    CardComponent,
    FilterPipe,
    InterpolatePipe,
    ShareLinkComponent,
    CollectionPlayerMetadataComponent,
    BrowserCompatibilityComponent,
    QrCodeModalComponent,
    CdnprefixPipe,
    RedirectComponent,
    CustomMultiSelectComponent
  ],
  exports: [
    AppLoaderComponent,
    AnnouncementInboxCardComponent,
    DateFormatPipe,
    DateFilterXtimeAgoPipe,
    PageSectionComponent,
    NoResultComponent,
    CollectionTreeComponent,
    FancyTreeComponent,
    PlayerComponent,
    CardComponent,
    FilterPipe,
    ShareLinkComponent,
    CollectionPlayerMetadataComponent,
    BrowserCompatibilityComponent,
    QrCodeModalComponent,
    CdnprefixPipe,
    InterpolatePipe,
    RedirectComponent,
    CustomMultiSelectComponent,
    MatAutocompleteModule,
    MatBadgeModule,
    MatBottomSheetModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    MatExpansionModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatSortModule,
    MatStepperModule,
    MatTableModule,
    MatTabsModule,
    MatToolbarModule,
    MatTooltipModule,
    MatTreeModule,
    MatCardModule
  ]
})
export class SharedModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: SharedModule,
      providers: [
        ResourceService,
        ConfigService,
        FileUploadService,
        ToasterService,
        Ng2IzitoastService,
        PaginationService,
        RouterNavigationService,
        WindowScrollService,
        NavigationHelperService,
        CacheService,
        UtilService,
        ContentUtilsServiceService,
        DeviceDetectorModule,
        DeviceDetectorService,
        BrowserCacheTtlService,
        ExternalUrlPreviewService
      ]
    };
  }
}
