export const mockRes = {
    orgDetailsSuccess: {
        'id': 'api.org.search',
        'ver': 'v1',
        'ts': '2018-09-24 11:32:38:448+0000',
        'params': {
            'resmsgid': null,
            'msgid': 'c867c823-ce6f-be6d-0a35-2098d4d67874',
            'err': null,
            'status': 'success',
            'errmsg': null
        },
        'responseCode': 'OK',
        'result': {
            'response': {
                'count': 8,
                'content': [
                    {
                        'dateTime': null,
                        'preferredLanguage': null,
                        'approvedBy': null,
                        'channel': 'TRUE',
                        'description': null,
                        'updatedDate': null,
                        'addressId': null,
                        'orgType': null,
                        'provider': null,
                        'orgCode': null,
                        'theme': null,
                        'id': '012349654805897216242',
                        'communityId': null,
                        'isApproved': null,
                        'slug': 'true',
                        'identifier': '012349654805897216242',
                        'thumbnail': null,
                        'orgName': 'OM org',
                        'updatedBy': null,
                        'externalId': null,
                        'isRootOrg': false,
                        'rootOrgId': '012315809814749184151',
                        'approvedDate': null,
                        'imgUrl': null,
                        'homeUrl': null,
                        'isDefault': null,
                        'contactDetail': [],
                        'createdDate': '2017-10-09 05:15:26:221+0000',
                        'createdBy': null,
                        'parentOrgId': null,
                        'hashTagId': '012349654805897216242',
                        'noOfMembers': null,
                        'status': 1
                    },
                    {
                        'dateTime': null,
                        'preferredLanguage': null,
                        'approvedBy': null,
                        'channel': 'TRUE',
                        'description': 'test',
                        'updatedDate': '2017-12-08 11:27:07:812+0000',
                        'addressId': null,
                        'orgType': null,
                        'provider': 'nnn',
                        'orgCode': null,
                        'locationId': '01239169805534003213',
                        'theme': null,
                        'id': '01232004891662745660',
                        'communityId': null,
                        'isApproved': null,
                        'slug': 'true',
                        'identifier': '01232004891662745660',
                        'thumbnail': null,
                        'orgName': 'QA Ordg demo',
                        'updatedBy': '95132a4e-0aa7-4526-b900-705ac6a3f2e8',
                        'externalId': '1578',
                        'isRootOrg': false,
                        'rootOrgId': '012315809814749184151',
                        'approvedDate': null,
                        'imgUrl': null,
                        'homeUrl': null,
                        'isDefault': null,
                        'contactDetail': [],
                        'createdDate': '2017-08-28 09:18:50:504+0000',
                        'createdBy': null,
                        'parentOrgId': null,
                        'hashTagId': '01232004891662745660',
                        'noOfMembers': null,
                        'status': null
                    },
                    {
                        'dateTime': null,
                        'preferredLanguage': null,
                        'approvedBy': null,
                        'channel': 'TRUE',
                        'description': 'test',
                        'updatedDate': null,
                        'addressId': null,
                        'orgType': null,
                        'provider': 'nnn',
                        'orgCode': null,
                        'theme': null,
                        'id': '01231851020160204812',
                        'communityId': null,
                        'isApproved': null,
                        'slug': 'true',
                        'identifier': '01231851020160204812',
                        'thumbnail': null,
                        'orgName': 'QA Ord',
                        'updatedBy': null,
                        'externalId': '155',
                        'isRootOrg': false,
                        'rootOrgId': '012315809814749184151',
                        'approvedDate': null,
                        'imgUrl': null,
                        'homeUrl': null,
                        'isDefault': null,
                        'contactDetail': null,
                        'createdDate': '2017-08-26 05:13:07:102+0000',
                        'createdBy': null,
                        'parentOrgId': null,
                        'hashTagId': '01231851020160204812',
                        'noOfMembers': null,
                        'status': null
                    },
                    {
                        'dateTime': null,
                        'preferredLanguage': null,
                        'approvedBy': null,
                        'channel': null,
                        'description': '111',
                        'updatedDate': null,
                        'addressId': null,
                        'orgType': null,
                        'provider': 'true',
                        'locationId': null,
                        'orgCode': null,
                        'theme': null,
                        'id': '0125485231127019526',
                        'communityId': null,
                        'isApproved': null,
                        'slug': null,
                        'identifier': '0125485231127019526',
                        'thumbnail': null,
                        'orgName': 'Test_17_7_2018',
                        'updatedBy': null,
                        'locationIds': [],
                        'externalId': 'abcd',
                        'isRootOrg': false,
                        'rootOrgId': '012315809814749184151',
                        'approvedDate': null,
                        'imgUrl': null,
                        'homeUrl': null,
                        'orgTypeId': null,
                        'isDefault': null,
                        'contactDetail': [],
                        'createdDate': '2018-07-17 04:27:01:016+0000',
                        'createdBy': '230cb747-6ce9-4e1c-91a8-1067ae291cb9',
                        'parentOrgId': null,
                        'hashTagId': '0125485231127019526',
                        'noOfMembers': null,
                        'status': 1
                    },
                    {
                        'dateTime': null,
                        'preferredLanguage': null,
                        'approvedBy': null,
                        'channel': null,
                        'description': '111',
                        'updatedDate': null,
                        'addressId': null,
                        'orgType': null,
                        'provider': 'true',
                        'locationId': null,
                        'orgCode': null,
                        'theme': null,
                        'id': '0125485163231232002',
                        'communityId': null,
                        'isApproved': null,
                        'slug': null,
                        'identifier': '0125485163231232002',
                        'thumbnail': null,
                        'orgName': 'Test_17_7',
                        'updatedBy': null,
                        'locationIds': [],
                        'externalId': 'kasghjagshj',
                        'isRootOrg': false,
                        'rootOrgId': '012315809814749184151',
                        'approvedDate': null,
                        'imgUrl': null,
                        'homeUrl': null,
                        'orgTypeId': null,
                        'isDefault': null,
                        'contactDetail': [],
                        'createdDate': '2018-07-17 04:16:33:328+0000',
                        'createdBy': '230cb747-6ce9-4e1c-91a8-1067ae291cb9',
                        'parentOrgId': null,
                        'hashTagId': '0125485163231232002',
                        'noOfMembers': null,
                        'status': 1
                    },
                    {
                        'dateTime': null,
                        'preferredLanguage': null,
                        'approvedBy': null,
                        'channel': 'TRUE',
                        'description': 'hello',
                        'updatedDate': null,
                        'addressId': null,
                        'orgType': null,
                        'provider': '11',
                        'orgCode': null,
                        'theme': null,
                        'id': '01231641129073049647',
                        'communityId': null,
                        'isApproved': null,
                        'slug': 'true',
                        'identifier': '01231641129073049647',
                        'thumbnail': null,
                        'orgName': 'QWE',
                        'updatedBy': null,
                        'externalId': '11',
                        'isRootOrg': false,
                        'rootOrgId': '012315809814749184151',
                        'approvedDate': null,
                        'imgUrl': null,
                        'homeUrl': null,
                        'isDefault': null,
                        'contactDetail': null,
                        'createdDate': '2017-08-23 06:00:26:848+0000',
                        'createdBy': null,
                        'parentOrgId': null,
                        'hashTagId': '01231641129073049647',
                        'noOfMembers': null,
                        'status': null
                    },
                    {
                        'dateTime': null,
                        'preferredLanguage': null,
                        'approvedBy': null,
                        'channel': 'TRUE',
                        'description': null,
                        'updatedDate': null,
                        'addressId': null,
                        'orgType': null,
                        'provider': null,
                        'orgCode': null,
                        'theme': null,
                        'id': '012349660063113216244',
                        'communityId': null,
                        'isApproved': null,
                        'slug': 'true',
                        'identifier': '012349660063113216244',
                        'thumbnail': null,
                        'orgName': 'OM org',
                        'updatedBy': null,
                        'externalId': null,
                        'isRootOrg': false,
                        'rootOrgId': '012315809814749184151',
                        'approvedDate': null,
                        'imgUrl': null,
                        'homeUrl': null,
                        'isDefault': null,
                        'contactDetail': [],
                        'createdDate': '2017-10-09 05:20:49:184+0000',
                        'createdBy': null,
                        'parentOrgId': null,
                        'hashTagId': '012349660063113216244',
                        'noOfMembers': null,
                        'status': 1
                    },
                    {
                        'dateTime': null,
                        'preferredLanguage': null,
                        'approvedBy': null,
                        'channel': 'TRUE',
                        'description': 'test',
                        'updatedDate': '2017-12-08 11:16:45:156+0000',
                        'addressId': null,
                        'orgType': null,
                        'provider': 'nnn',
                        'orgCode': null,
                        'locationId': '0123916990102568966',
                        'theme': null,
                        'id': '01232002070124134414',
                        'communityId': null,
                        'isApproved': null,
                        'slug': 'true',
                        'identifier': '01232002070124134414',
                        'thumbnail': null,
                        'orgName': 'Consumption Org',
                        'updatedBy': '230cb747-6ce9-4e1c-91a8-1067ae291cb9',
                        'externalId': '1555',
                        'isRootOrg': false,
                        'rootOrgId': '012315809814749184151',
                        'approvedDate': null,
                        'imgUrl': null,
                        'homeUrl': null,
                        'isDefault': null,
                        'contactDetail': [],
                        'createdDate': '2017-08-28 08:18:00:650+0000',
                        'createdBy': null,
                        'parentOrgId': null,
                        'hashTagId': '01232002070124134414',
                        'noOfMembers': null,
                        'status': null
                    }
                ]
            }
        }
    },
    userMockData: {

        'lastName': 'User',
        'loginId': 'ntptest102',
        'regOrgId': '0123653943740170242',
        'roles': [
            'public'
        ],
        'rootOrg': {
            'dateTime': null,
            'preferredLanguage': 'English',
            'approvedBy': null,
            'channel': 'ROOT_ORG',
            'description': 'Sunbird',
            'updatedDate': '2017-08-24 06:02:10:846+0000',
            'addressId': null,
            'orgType': null,
            'provider': null,
            'orgCode': 'sunbird',
            'theme': null,
            'id': 'ORG_001',
            'communityId': null,
            'isApproved': null,
            'slug': 'sunbird',
            'identifier': 'ORG_001',
            'thumbnail': null,
            'orgName': 'Sunbird',
            'updatedBy': 'user1',
            'externalId': null,
            'isRootOrg': true,
            'rootOrgId': null,
            'approvedDate': null,
            'imgUrl': null,
            'homeUrl': null,
            'isDefault': null,
            'contactDetail':
                '[{\'phone\':\'213124234234\',\'email\':\'test@test.com\'},{\'phone\':\'+91213124234234\',\'email\':\'test1@test.com\'}]',
            'createdDate': null,
            'createdBy': null,
            'parentOrgId': null,
            'hashTagId': 'b00bc992ef25f1a9a8d63291e20efc8d',
            'noOfMembers': 1,
            'status': null
        },
        'identifier': '874ed8a5-782e-4f6c-8f36-e0288455901e',
        'profileSummary': 'asdd',
        'tcUpdatedDate': null,
        'avatar': 'https://sunbirddev.blob.core.windows.net/user/874ed8a5-782e-4f6c-8f36-e0288455901e/File-01242833565242982418.png',
        'userName': 'ntptest102',
        'rootOrgId': 'ORG_001',
        'userId': '874ed8a5-782e-4f6c-8f36-e0288455901e',
        'emailVerified': null,
        'firstName': 'Cretation',
        'lastLoginTime': 1519809987692,
        'createdDate': '2017-10-31 10:47:04:723+0000',
        'createdBy': '5d7eb482-c2b8-4432-bf38-cc58f3c23b45',
        'organisationIds': ['01232002070124134414', '012315809814749184151']
    },
    getUserList: {
        'id': 'api.user.search',
        'ver': 'v1',
        'ts': '2018-07-03 09:51:55:738+0000',
        'params': {
            'resmsgid': null,
            'msgid': '1e1b8708-6342-931b-8b29-b0fef2dbbb9b',
            'err': null,
            'status': 'success',
            'errmsg': null
        },
        'responseCode': 'OK',
        'result': {
            'response': {
                'count': 3,
                'content': [
                    {
                        'lastName': '',
                        'webPages': [],
                        'tcStatus': null,
                        'education': [],
                        'gender': null,
                        'regOrgId': null,
                        'subject': [],
                        'roles': [
                            'CONTENT_CREATOR',
                            'CONTENT_CREATION',
                            'CONTENT_REVIEWER',
                            'CONTENT_REVIEW',
                            'FLAG_REVIEWER'
                        ],
                        'language': [],
                        'updatedDate': '2017-08-17 06:46:20:422+0000',
                        'skills': [],
                        'isDeleted': true,
                        'organisations': [],
                        'provider': null,
                        'countryCode': '+91',
                        'id': '27d5a117-e1a1-4202-8476-6be21fd76a5c',
                        'tempPassword': null,
                        'email': 'po******@gmail.com',
                        'identifier': '27d5a117-e1a1-4202-8476-6be21fd76a5c',
                        'thumbnail': null,
                        'address': [],
                        'jobProfile': [],
                        'profileSummary': null,
                        'tcUpdatedDate': null,
                        'avatar': 'https://ekstep-public-qa.s3-ap-south-1.amazonaws.com/media/comm-landing_1502271728363.png',
                        'rootOrgId': 'ORG_001',
                        'badges': [],
                        'emailVerified': null,
                        'firstName': 'poonam',
                        'lastLoginTime': null,
                        'createdDate': '2017-08-08 09:09:05:461+0000',
                        'createdBy': null,
                        'phone': '******8098',
                        'dob': null,
                        'grade': [],
                        'currentLoginTime': null,
                        'location': null,
                        'status': 0
                    },
                    {
                        'lastName': 'Test',
                        'webPages': [],
                        'tcStatus': null,
                        'education': [],
                        'gender': null,
                        'subject': [],
                        'roles': [
                            'PUBLIC'
                        ],
                        'channel': null,
                        'language': [],
                        'updatedDate': null,
                        'skills': [],
                        'badgeAssertions': [],
                        'isDeleted': false,
                        'organisations': [],
                        'countryCode': '+91',
                        'id': '3e6c6eb7-8c0c-45b6-9114-e36b59e1aa8b',
                        'tempPassword': null,
                        'email': '',
                        'phoneverified': null,
                        'identifier': '3e6c6eb7-8c0c-45b6-9114-e36b59e1aa8b',
                        'thumbnail': null,
                        'address': [],
                        'jobProfile': [],
                        'profileSummary': null,
                        'tcUpdatedDate': null,
                        'avatar': null,
                        'rootOrgId': 'ORG_001',
                        'emailVerified': false,
                        'firstName': 'User 3525',
                        'lastLoginTime': null,
                        'createdDate': '2018-06-07 18:52:54:407+0000',
                        'createdBy': '',
                        'phone': null,
                        'dob': null,
                        'grade': [],
                        'currentLoginTime': null,
                        'location': 'location',
                        'status': 1
                    },
                    {
                        'lastName': 'creator_org_001',
                        'webPages': [],
                        'tcStatus': null,
                        'education': [],
                        'gender': null,
                        'subject': [],
                        'roles': [
                            'PUBLIC'
                        ],
                        'channel': null,
                        'language': [],
                        'updatedDate': '2018-03-23 12:05:34:090+0000',
                        'skills': [
                            {
                                'skillName': 'test',
                                'addedAt': '2018-05-21',
                                'endorsersList': [
                                    {
                                        'endorseDate': '2018-05-21',
                                        'userId': 'b2479136-8608-41c0-b3b1-283f38c338ed'
                                    },
                                    {
                                        'endorseDate': '2018-05-23',
                                        'userId': '5d7eb482-c2b8-4432-bf38-cc58f3c23b45'
                                    },
                                    {
                                        'endorseDate': '2018-05-23',
                                        'userId': '6d4da241-a31b-4041-bbdb-dd3a898b3f85'
                                    }
                                ],
                                'addedBy': 'b2479136-8608-41c0-b3b1-283f38c338ed',
                                'endorsementcount': 2,
                                'id': '71cfd844ec57b7828ae93fce192e961932de293e45635bc06012a197d4adb929',
                                'skillNameToLowercase': 'test',
                                'userId': 'b2479136-8608-41c0-b3b1-283f38c338ed'
                            }
                        ],
                        'badgeAssertions': [],
                        'isDeleted': null,
                        'organisations': [
                            {
                                'organisationId': 'ORG_001',
                                'updatedBy': null,
                                'addedByName': 'Rg==',
                                'addedBy': '781c21fc-5054-4ee0-9a02-fbb1006a4fdd',
                                'roles': [
                                    'BOOK_CREATOR',
                                    'COURSE_MENTOR'
                                ],
                                'approvedBy': '781c21fc-5054-4ee0-9a02-fbb1006a4fdd',
                                'updatedDate': null,
                                'userId': 'b2479136-8608-41c0-b3b1-283f38c338ed',
                                'approvaldate': '2018-03-16 10:44:22:327+0000',
                                'isDeleted': false,
                                'isRejected': false,
                                'id': '0124616467103580163',
                                'position': null,
                                'isApproved': true,
                                'orgjoindate': '2018-03-16 10:44:22:327+0000',
                                'orgLeftDate': null
                            }
                        ],
                        'countryCode': '+91',
                        'id': 'b2479136-8608-41c0-b3b1-283f38c338ed',
                        'tempPassword': null,
                        'email': null,
                        'phoneverified': null,
                        'identifier': 'b2479136-8608-41c0-b3b1-283f38c338ed',
                        'thumbnail': null,
                        'address': [
                            {
                                'country': null,
                                'updatedBy': 'b2479136-8608-41c0-b3b1-283f38c338ed',
                                'city': 'xcv',
                                'updatedDate': '2018-03-23 12:05:34:100+0000',
                                'userId': 'b2479136-8608-41c0-b3b1-283f38c338ed',
                                'zipcode': null,
                                'addType': 'current',
                                'createdDate': '2018-03-23 12:05:10:103+0000',
                                'isDeleted': null,
                                'createdBy': 'b2479136-8608-41c0-b3b1-283f38c338ed',
                                'addressLine1': 'vxcv',
                                'addressLine2': null,
                                'id': '0124666424917360640',
                                'state': null
                            },
                            {
                                'country': null,
                                'updatedBy': null,
                                'city': 'sdfsd',
                                'updatedDate': null,
                                'userId': 'b2479136-8608-41c0-b3b1-283f38c338ed',
                                'zipcode': null,
                                'addType': 'permanent',
                                'createdDate': '2018-03-23 12:05:34:108+0000',
                                'isDeleted': null,
                                'createdBy': 'b2479136-8608-41c0-b3b1-283f38c338ed',
                                'addressLine1': 'zcfsdf',
                                'addressLine2': null,
                                'id': '0124666450913771521',
                                'state': null
                            }
                        ],
                        'jobProfile': [],
                        'profileSummary': null,
                        'tcUpdatedDate': null,
                        'avatar': null,
                        'rootOrgId': 'ORG_001',
                        'emailVerified': false,
                        'firstName': 'book',
                        'lastLoginTime': null,
                        'createdDate': '2018-03-16 10:43:28:156+0000',
                        'createdBy': '',
                        'phone': '',
                        'dob': null,
                        'grade': [],
                        'currentLoginTime': null,
                        'location': null,
                        'status': 1
                    }
                ]
            }
        }
    }
};
