import { Component, OnInit } from "@angular/core";
import { COLUMN_TYPE, LayoutService, ResourceService } from "@sunbird/shared";
import { FormGroup, FormBuilder } from "@angular/forms";
import { QuestionnaireService } from "../questionnaire.service";

@Component({
  selector: "app-questionnaire",
  templateUrl: "./questionnaire.component.html",
  styleUrls: ["./questionnaire.component.scss"],
})
export class QuestionnaireComponent implements OnInit {
  pageTitleSrc: string = "Observation Form";
  svgToDisplay: string = "textbooks-banner-img.svg";
  layoutConfiguration: any;
  FIRST_PANEL_LAYOUT;
  SECOND_PANEL_LAYOUT;
  questionnaireForm: FormGroup;

  constructor(
    public layoutService: LayoutService,
    public fb: FormBuilder,
    public qService: QuestionnaireService,
    public resourceService: ResourceService
  ) {}

  ngOnInit() {
    this.initConfiguration();
    this.questionnaireForm = this.fb.group({});
  }

  private initConfiguration() {
    this.layoutConfiguration = this.layoutService.initlayoutConfig();
    this.redoLayout();
  }

  redoLayout() {
    if (this.layoutConfiguration != null) {
      this.FIRST_PANEL_LAYOUT = this.layoutService.redoLayoutCSS(
        0,
        this.layoutConfiguration,
        COLUMN_TYPE.threeToNine,
        true
      );
      this.SECOND_PANEL_LAYOUT = this.layoutService.redoLayoutCSS(
        1,
        this.layoutConfiguration,
        COLUMN_TYPE.threeToNine,
        true
      );
    } else {
      this.FIRST_PANEL_LAYOUT = this.layoutService.redoLayoutCSS(
        0,
        null,
        COLUMN_TYPE.fullLayout
      );
      this.SECOND_PANEL_LAYOUT = this.layoutService.redoLayoutCSS(
        1,
        null,
        COLUMN_TYPE.fullLayout
      );
    }
  }

  onSubmit() {
    let data = this.qService.createpayload(
      this.questions,
      this.questionnaireForm.value
    );
    console.log(data);
  }

  questions = [
    // {
    //   _id: "",
    //   question: "",
    //   isCompleted: "",
    //   showRemarks: "",
    //   options: "",
    //   sliderOptions: "",
    //   children: "",
    //   questionGroup: "",
    //   fileName: "",
    //   instanceQuestions: "",
    //   isAGeneralQuestion: "",
    //   autoCapture: "",
    //   allowAudioRecording: "",
    //   prefillFromEntityProfile: "",
    //   entityFieldName: "",
    //   isEditable: "",
    //   showQuestionInPreview: "",
    //   deleted: "",
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "",
    //   canBeNotApplicable: "",
    //   visibleIf: "",
    //   validation: "",
    //   dateFormat: "",
    //   externalId: "",
    //   tip: "",
    //   hint: "",
    //   responseType: "pageQuestions",
    //   modeOfCollection: "",
    //   accessibility: "",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "",
    //   updatedAt: "",
    //   createdAt: "",
    //   __v: "",
    //   createdFromQuestionId: "",
    //   evidenceMethod: "",
    //   payload: "",
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    //   pageQuestions: [
    //     {
    //       _id: "6054abd9823d601f0af5c391-p",
    //       question: ["Enter the date of observation", ""],
    //       isCompleted: false,
    //       showRemarks: false,
    //       options: [],
    //       sliderOptions: [],
    //       children: [],
    //       questionGroup: ["A1"],
    //       fileName: [],
    //       instanceQuestions: [],
    //       isAGeneralQuestion: false,
    //       autoCapture: false,
    //       allowAudioRecording: false,
    //       prefillFromEntityProfile: false,
    //       entityFieldName: "",
    //       isEditable: true,
    //       showQuestionInPreview: false,
    //       deleted: false,
    //       remarks: "",
    //       value: "",
    //       usedForScoring: "",
    //       questionType: "auto",
    //       canBeNotApplicable: "false",
    //       visibleIf: "",
    //       validation: {
    //         required: true,
    //         max: "",
    //         min: "",
    //       },
    //       dateFormat: "",
    //       externalId: "Q1_1616157220157-1616161753196",
    //       tip: "",
    //       hint: "",
    //       responseType: "date",
    //       modeOfCollection: "onfield",
    //       accessibility: "No",
    //       rubricLevel: "",
    //       sectionHeader: "",
    //       page: "p1",
    //       questionNumber: "1",
    //       updatedAt: "2021-03-19T13:49:13.223Z",
    //       createdAt: "2021-03-19T12:33:46.588Z",
    //       __v: 0,
    //       createdFromQuestionId: "60549a2a823d601f0af5c367",
    //       evidenceMethod: "OB",
    //       payload: {
    //         criteriaId: "6054abd9823d601f0af5c39e",
    //         responseType: "date",
    //         evidenceMethod: "OB",
    //         rubricLevel: "",
    //       },
    //       startTime: "",
    //       endTime: "",
    //       gpsLocation: "",
    //       file: "",
    //     },
    //     {
    //       _id: "6054abd9823d601f0af5c393-p",
    //       question: ["Which class does your child study in?", ""],
    //       isCompleted: false,
    //       showRemarks: false,
    //       options: [],
    //       sliderOptions: [],
    //       children: [],
    //       questionGroup: ["A1"],
    //       fileName: [],
    //       instanceQuestions: [],
    //       isAGeneralQuestion: false,
    //       autoCapture: false,
    //       allowAudioRecording: false,
    //       prefillFromEntityProfile: false,
    //       entityFieldName: "",
    //       isEditable: true,
    //       showQuestionInPreview: false,
    //       deleted: false,
    //       remarks: "",
    //       value: "",
    //       usedForScoring: "",
    //       questionType: "auto",
    //       canBeNotApplicable: "false",
    //       visibleIf: "",
    //       validation: {
    //         required: true,
    //         IsNumber: "true",
    //       },
    //       externalId: "Q2_1616157220157-1616161753199",
    //       tip: "",
    //       hint: "",
    //       responseType: "number",
    //       modeOfCollection: "onfield",
    //       accessibility: "No",
    //       rubricLevel: "",
    //       sectionHeader: "",
    //       page: "p1",
    //       questionNumber: "2",
    //       updatedAt: "2021-03-19T13:49:13.224Z",
    //       createdAt: "2021-03-19T12:33:46.611Z",
    //       __v: 0,
    //       createdFromQuestionId: "60549a2a823d601f0af5c369",
    //       evidenceMethod: "OB",
    //       payload: {
    //         criteriaId: "6054abd9823d601f0af5c39e",
    //         responseType: "number",
    //         evidenceMethod: "OB",
    //         rubricLevel: "",
    //       },
    //       startTime: "",
    //       endTime: "",
    //       gpsLocation: "",
    //       file: "",
    //     },
    //     {
    //       _id: "6054abd9823d601f0af5c394-p",
    //       question: [
    //         "Are you currently living in the vicinity of the school?",
    //         "",
    //       ],
    //       isCompleted: false,
    //       showRemarks: false,
    //       options: [
    //         {
    //           value: "R1",
    //           label: "Yes",
    //         },
    //         {
    //           value: "R2",
    //           label: "No",
    //         },
    //       ],
    //       sliderOptions: [],
    //       children: ["6054abd9823d601f0af5c395"],
    //       questionGroup: ["A1"],
    //       fileName: [],
    //       instanceQuestions: [],
    //       isAGeneralQuestion: false,
    //       autoCapture: false,
    //       allowAudioRecording: false,
    //       prefillFromEntityProfile: false,
    //       entityFieldName: "",
    //       isEditable: true,
    //       showQuestionInPreview: false,
    //       deleted: false,
    //       remarks: "",
    //       value: "",
    //       usedForScoring: "",
    //       questionType: "auto",
    //       canBeNotApplicable: "false",
    //       visibleIf: "",
    //       validation: {
    //         required: true,
    //       },
    //       externalId: "Q3_1616157220157-1616161753202",
    //       tip: "Use the name of the locality where the school is",
    //       hint: "",
    //       responseType: "radio",
    //       modeOfCollection: "onfield",
    //       accessibility: "No",
    //       rubricLevel: "",
    //       sectionHeader: "",
    //       page: "p1",
    //       questionNumber: "3",
    //       updatedAt: "2021-03-19T13:49:13.224Z",
    //       createdAt: "2021-03-19T12:33:46.622Z",
    //       __v: 0,
    //       createdFromQuestionId: "60549a2a823d601f0af5c36a",
    //       evidenceMethod: "OB",
    //       payload: {
    //         criteriaId: "6054abd9823d601f0af5c39e",
    //         responseType: "radio",
    //         evidenceMethod: "OB",
    //         rubricLevel: "",
    //       },
    //       startTime: "",
    //       endTime: "",
    //       gpsLocation: "",
    //       file: "",
    //     },
    //     {
    //       _id: "6054abd9823d601f0af5c395-p",
    //       question: ["Are you planning to come back?", ""],
    //       isCompleted: false,
    //       showRemarks: false,
    //       options: [
    //         {
    //           value: "R1",
    //           label: "Yes",
    //         },
    //         {
    //           value: "R2",
    //           label: "No",
    //         },
    //       ],
    //       sliderOptions: [],
    //       children: [],
    //       questionGroup: ["A1"],
    //       fileName: [],
    //       instanceQuestions: [],
    //       isAGeneralQuestion: false,
    //       autoCapture: false,
    //       allowAudioRecording: false,
    //       prefillFromEntityProfile: false,
    //       entityFieldName: "",
    //       isEditable: true,
    //       showQuestionInPreview: false,
    //       deleted: false,
    //       remarks: "",
    //       value: "",
    //       usedForScoring: "",
    //       questionType: "auto",
    //       canBeNotApplicable: "false",
    //       visibleIf: [
    //         {
    //           operator: "===",
    //           value: ["R2"],
    //           _id: "6054abd9823d601f0af5c394-p",
    //         },
    //       ],
    //       validation: {
    //         required: false,
    //       },
    //       externalId: "Q4_1616157220157-1616161753203",
    //       tip: "",
    //       hint: "This becomes a risk if the answer is no",
    //       responseType: "radio",
    //       modeOfCollection: "onfield",
    //       accessibility: "No",
    //       rubricLevel: "",
    //       sectionHeader: "",
    //       page: "p1",
    //       questionNumber: "4",
    //       updatedAt: "2021-03-19T13:49:13.224Z",
    //       createdAt: "2021-03-19T12:33:46.633Z",
    //       __v: 0,
    //       createdFromQuestionId: "60549a2a823d601f0af5c36b",
    //       evidenceMethod: "OB",
    //       payload: {
    //         criteriaId: "6054abd9823d601f0af5c39e",
    //         responseType: "radio",
    //         evidenceMethod: "OB",
    //         rubricLevel: "",
    //       },
    //       startTime: "",
    //       endTime: "",
    //       gpsLocation: "",
    //       file: "",
    //     },
    //     {
    //       _id: "6054abd9823d601f0af5c396-p",
    //       question: ["What type of device is available at home?", ""],
    //       isCompleted: false,
    //       showRemarks: true,
    //       options: [
    //         {
    //           value: "R1",
    //           label: "Simple mobile phone without internet/data pack",
    //         },
    //         {
    //           value: "R2",
    //           label: "Smart phone with internet/data pack",
    //         },
    //         {
    //           value: "R3",
    //           label: "Smart phone without internet/data pack",
    //         },
    //         {
    //           value: "R4",
    //           label: "TV",
    //         },
    //         {
    //           value: "R5",
    //           label: "Radio",
    //         },
    //       ],
    //       sliderOptions: [],
    //       children: [],
    //       questionGroup: ["A1"],
    //       fileName: [],
    //       instanceQuestions: [],
    //       isAGeneralQuestion: false,
    //       autoCapture: false,
    //       allowAudioRecording: false,
    //       prefillFromEntityProfile: false,
    //       entityFieldName: "",
    //       isEditable: true,
    //       showQuestionInPreview: false,
    //       deleted: false,
    //       remarks: "",
    //       value: "",
    //       usedForScoring: "",
    //       questionType: "auto",
    //       canBeNotApplicable: "false",
    //       visibleIf: "",
    //       validation: {
    //         required: true,
    //       },
    //       file: {
    //         required: true,
    //         type: ["image/jpeg", "docx", "pdf", "ppt"],
    //         minCount: 0,
    //         maxCount: 10,
    //         caption: "FALSE",
    //       },
    //       externalId: "Q5_1616157220157-1616161753205",
    //       tip: "",
    //       hint: "The devices that are available or can be easily arranged in the household.",
    //       responseType: "multiselect",
    //       modeOfCollection: "onfield",
    //       accessibility: "No",
    //       rubricLevel: "",
    //       sectionHeader: "",
    //       page: "p1",
    //       questionNumber: "5",
    //       updatedAt: "2021-03-19T13:49:13.224Z",
    //       createdAt: "2021-03-19T12:33:46.646Z",
    //       __v: 0,
    //       createdFromQuestionId: "60549a2a823d601f0af5c36c",
    //       evidenceMethod: "OB",
    //       payload: {
    //         criteriaId: "6054abd9823d601f0af5c39e",
    //         responseType: "multiselect",
    //         evidenceMethod: "OB",
    //         rubricLevel: "",
    //       },
    //       startTime: "",
    //       endTime: "",
    //       gpsLocation: "",
    //     },
    //     {
    //       _id: "6054abd9823d601f0af5c397-p",
    //       question: ["Does the child have a quiet place to study?", ""],
    //       isCompleted: false,
    //       showRemarks: true,
    //       options: [
    //         {
    //           value: "R1",
    //           label: "Yes",
    //         },
    //         {
    //           value: "R2",
    //           label: "No",
    //         },
    //       ],
    //       sliderOptions: [],
    //       children: [],
    //       questionGroup: ["A1"],
    //       fileName: [],
    //       instanceQuestions: [],
    //       isAGeneralQuestion: false,
    //       autoCapture: false,
    //       allowAudioRecording: false,
    //       prefillFromEntityProfile: false,
    //       entityFieldName: "",
    //       isEditable: true,
    //       showQuestionInPreview: false,
    //       deleted: false,
    //       remarks: "",
    //       value: "",
    //       usedForScoring: "",
    //       questionType: "auto",
    //       canBeNotApplicable: "false",
    //       visibleIf: "",
    //       validation: {
    //         required: true,
    //       },
    //       externalId: "Q6_1616157220157-1616161753206",
    //       tip: "",
    //       hint: "",
    //       responseType: "radio",
    //       modeOfCollection: "onfield",
    //       accessibility: "No",
    //       rubricLevel: "",
    //       sectionHeader: "",
    //       page: "p1",
    //       questionNumber: "6",
    //       updatedAt: "2021-03-19T13:49:13.224Z",
    //       createdAt: "2021-03-19T12:33:46.657Z",
    //       __v: 0,
    //       createdFromQuestionId: "60549a2a823d601f0af5c36d",
    //       evidenceMethod: "OB",
    //       payload: {
    //         criteriaId: "6054abd9823d601f0af5c39e",
    //         responseType: "radio",
    //         evidenceMethod: "OB",
    //         rubricLevel: "",
    //       },
    //       startTime: "",
    //       endTime: "",
    //       gpsLocation: "",
    //       file: "",
    //     },
    //     {
    //       _id: "6054abd9823d601f0af5c398-p",
    //       question: [
    //         "Were you able to enrol your child in courses on DIKSHA?",
    //         "",
    //       ],
    //       isCompleted: false,
    //       showRemarks: false,
    //       options: [
    //         {
    //           value: "R1",
    //           label: "Yes",
    //         },
    //         {
    //           value: "R2",
    //           label: "No",
    //         },
    //       ],
    //       sliderOptions: [],
    //       children: ["6054abd9823d601f0af5c399"],
    //       questionGroup: ["A1"],
    //       fileName: [],
    //       instanceQuestions: [],
    //       isAGeneralQuestion: false,
    //       autoCapture: false,
    //       allowAudioRecording: false,
    //       prefillFromEntityProfile: false,
    //       entityFieldName: "",
    //       isEditable: true,
    //       showQuestionInPreview: false,
    //       deleted: false,
    //       remarks: "",
    //       value: "",
    //       usedForScoring: "",
    //       questionType: "auto",
    //       canBeNotApplicable: "false",
    //       visibleIf: "",
    //       validation: {
    //         required: true,
    //       },
    //       externalId: "Q7_1616157220157-1616161753207",
    //       tip: "",
    //       hint: "",
    //       responseType: "radio",
    //       modeOfCollection: "onfield",
    //       accessibility: "No",
    //       rubricLevel: "",
    //       sectionHeader: "",
    //       page: "p1",
    //       questionNumber: "7",
    //       updatedAt: "2021-03-19T13:49:13.224Z",
    //       createdAt: "2021-03-19T12:33:46.677Z",
    //       __v: 0,
    //       createdFromQuestionId: "60549a2a823d601f0af5c36e",
    //       evidenceMethod: "OB",
    //       payload: {
    //         criteriaId: "6054abd9823d601f0af5c39e",
    //         responseType: "radio",
    //         evidenceMethod: "OB",
    //         rubricLevel: "",
    //       },
    //       startTime: "",
    //       endTime: "",
    //       gpsLocation: "",
    //       file: "",
    //     },
    //     {
    //       _id: "6054abd9823d601f0af5c399-p",
    //       question: [
    //         "What are the challenges that you are facing in enrolment?",
    //         "",
    //       ],
    //       isCompleted: false,
    //       showRemarks: true,
    //       options: [
    //         {
    //           value: "R1",
    //           label: "Not able to use the app",
    //         },
    //         {
    //           value: "R2",
    //           label: "Not aware of classrooms on DIKSHA",
    //         },
    //         {
    //           value: "R3",
    //           label: "Not aware of the enrolment process in the classroom",
    //         },
    //         {
    //           value: "R4",
    //           label: "Not aware of enrolment process in the courses",
    //         },
    //         {
    //           value: "R5",
    //           label: "Don’t find the courses useful",
    //         },
    //         {
    //           value: "R6",
    //           label: "Others",
    //         },
    //       ],
    //       sliderOptions: [],
    //       children: [],
    //       questionGroup: ["A1"],
    //       fileName: [],
    //       instanceQuestions: [],
    //       isAGeneralQuestion: false,
    //       autoCapture: false,
    //       allowAudioRecording: false,
    //       prefillFromEntityProfile: false,
    //       entityFieldName: "",
    //       isEditable: true,
    //       showQuestionInPreview: false,
    //       deleted: false,
    //       remarks: "",
    //       value: "",
    //       usedForScoring: "",
    //       questionType: "auto",
    //       canBeNotApplicable: "false",
    //       visibleIf: [
    //         {
    //           operator: "===",
    //           value: ["R2"],
    //           _id: "6054abd9823d601f0af5c398",
    //         },
    //       ],
    //       validation: {
    //         required: true,
    //       },
    //       externalId: "Q8_1616157220157-1616161753209",
    //       tip: "",
    //       hint: "",
    //       responseType: "multiselect",
    //       modeOfCollection: "onfield",
    //       accessibility: "No",
    //       rubricLevel: "",
    //       sectionHeader: "",
    //       page: "p1",
    //       questionNumber: "8",
    //       updatedAt: "2021-03-19T13:49:13.224Z",
    //       createdAt: "2021-03-19T12:33:46.689Z",
    //       __v: 0,
    //       createdFromQuestionId: "60549a2a823d601f0af5c36f",
    //       evidenceMethod: "OB",
    //       payload: {
    //         criteriaId: "6054abd9823d601f0af5c39e",
    //         responseType: "multiselect",
    //         evidenceMethod: "OB",
    //         rubricLevel: "",
    //       },
    //       startTime: "",
    //       endTime: "",
    //       gpsLocation: "",
    //       file: "",
    //     },
    //     {
    //       _id: "6054abd9823d601f0af5c39a-p",
    //       question: [
    //         "On basis of the responses received above,  do you think this student is a potential drop out?",
    //         "",
    //       ],
    //       isCompleted: false,
    //       showRemarks: true,
    //       options: [
    //         {
    //           value: "R1",
    //           label: "Yes",
    //         },
    //         {
    //           value: "R2",
    //           label: "No",
    //         },
    //       ],
    //       sliderOptions: [],
    //       children: [],
    //       questionGroup: ["A1"],
    //       fileName: [],
    //       instanceQuestions: [],
    //       isAGeneralQuestion: false,
    //       autoCapture: false,
    //       allowAudioRecording: false,
    //       prefillFromEntityProfile: false,
    //       entityFieldName: "",
    //       isEditable: true,
    //       showQuestionInPreview: false,
    //       deleted: false,
    //       remarks: "",
    //       value: "",
    //       usedForScoring: "",
    //       questionType: "auto",
    //       canBeNotApplicable: "false",
    //       visibleIf: "",
    //       validation: {
    //         required: true,
    //       },
    //       externalId: "Q9_1616157220157-1616161753210",
    //       tip: "Fill this based on the  parents' answers",
    //       hint: "",
    //       responseType: "radio",
    //       modeOfCollection: "onfield",
    //       accessibility: "No",
    //       rubricLevel: "",
    //       sectionHeader: "",
    //       page: "p1",
    //       questionNumber: "9",
    //       updatedAt: "2021-03-19T13:49:13.224Z",
    //       createdAt: "2021-03-19T12:33:46.706Z",
    //       __v: 0,
    //       createdFromQuestionId: "60549a2a823d601f0af5c370",
    //       evidenceMethod: "OB",
    //       payload: {
    //         criteriaId: "6054abd9823d601f0af5c39e",
    //         responseType: "radio",
    //         evidenceMethod: "OB",
    //         rubricLevel: "",
    //       },
    //       startTime: "",
    //       endTime: "",
    //       gpsLocation: "",
    //       file: "",
    //     },
    //   ],
    // },
    {
      _id: "",
      question: "",
      isCompleted: "",
      showRemarks: "",
      options: "",
      sliderOptions: "",
      children: "",
      questionGroup: "",
      fileName: "",
      instanceQuestions: "",
      isAGeneralQuestion: "",
      autoCapture: "",
      allowAudioRecording: "",
      prefillFromEntityProfile: "",
      entityFieldName: "",
      isEditable: "",
      showQuestionInPreview: "",
      deleted: "",
      remarks: "",
      value: "",
      usedForScoring: "",
      questionType: "",
      canBeNotApplicable: "",
      visibleIf: "",
      validation: "",
      dateFormat: "",
      externalId: "",
      tip: "",
      hint: "",
      responseType: "pageQuestions",
      modeOfCollection: "",
      accessibility: "",
      rubricLevel: "",
      sectionHeader: "",
      page: "p2",
      questionNumber: "",
      updatedAt: "",
      createdAt: "",
      __v: "",
      createdFromQuestionId: "",
      evidenceMethod: "",
      payload: "",
      startTime: "",
      endTime: "",
      gpsLocation: "",
      file: "",
      pageQuestions: [
        {
          _id: "6054abd9823d601f0af5c392",
          question: ["Add the student interview responses", ""],
          isCompleted: false,
          showRemarks: false,
          options: [],
          sliderOptions: [],
          children: [],
          questionGroup: ["A1"],
          fileName: [],
          instanceQuestions: [
            {
              _id: "6054abd9823d601f0af5c39b-pm",
              question: ["How would you rate the course taken?", ""],
              isCompleted: false,
              showRemarks: false,
              options: [],
              sliderOptions: [],
              children: [],
              questionGroup: ["A1"],
              fileName: [],
              instanceQuestions: [],
              isAGeneralQuestion: false,
              autoCapture: false,
              allowAudioRecording: false,
              prefillFromEntityProfile: false,
              entityFieldName: "",
              isEditable: true,
              showQuestionInPreview: false,
              deleted: false,
              remarks: "",
              value: "",
              usedForScoring: "",
              questionType: "auto",
              canBeNotApplicable: "false",
              visibleIf: "",
              validation: {
                required: true,
                max: "5",
                min: "1",
              },
              externalId: "Q12_1616157220157-1616161753212",
              tip: "",
              hint: "",
              responseType: "slider",
              modeOfCollection: "onfield",
              accessibility: "No",
              rubricLevel: "",
              sectionHeader: "",
              page: "p2",
              questionNumber: "10b",
              updatedAt: "2021-03-19T13:49:13.224Z",
              createdAt: "2021-03-19T13:41:46.341Z",
              __v: 0,
              createdFromQuestionId: "6054aa1a823d601f0af5c38e",
              evidenceMethod: "OB",
              payload: {
                criteriaId: "6054abd9823d601f0af5c39f",
                responseType: "slider",
                evidenceMethod: "OB",
                rubricLevel: "",
              },
              startTime: "",
              endTime: "",
              gpsLocation: "",
              file: "",
            },
            {
              _id: "6054abd9823d601f0af5c39c-pm",
              question: ["How many courses have you taken?", ""],
              isCompleted: false,
              showRemarks: false,
              options: [],
              sliderOptions: [],
              children: [],
              questionGroup: ["A1"],
              fileName: [],
              instanceQuestions: [],
              isAGeneralQuestion: false,
              autoCapture: false,
              allowAudioRecording: false,
              prefillFromEntityProfile: false,
              entityFieldName: "",
              isEditable: true,
              showQuestionInPreview: false,
              deleted: false,
              remarks: "",
              value: "",
              usedForScoring: "",
              questionType: "auto",
              canBeNotApplicable: "false",
              visibleIf: "",
              validation: {
                required: true,
                IsNumber: "true",
              },
              externalId: "Q13_1616157220157-1616161753214",
              tip: "",
              hint: "",
              responseType: "number",
              modeOfCollection: "onfield",
              accessibility: "No",
              rubricLevel: "",
              sectionHeader: "",
              page: "p2",
              questionNumber: "10c",
              updatedAt: "2021-03-19T13:49:13.224Z",
              createdAt: "2021-03-19T13:41:46.360Z",
              __v: 0,
              createdFromQuestionId: "6054aa1a823d601f0af5c38f",
              evidenceMethod: "OB",
              payload: {
                criteriaId: "6054abd9823d601f0af5c39f",
                responseType: "number",
                evidenceMethod: "OB",
                rubricLevel: "",
              },
              startTime: "",
              endTime: "",
              gpsLocation: "",
              file: "",
            },
            {
              _id: "6054abd9823d601f0af5c39d-pm",
              question: ["Which courses did you go through?", ""],
              isCompleted: false,
              showRemarks: false,
              options: [],
              sliderOptions: [],
              children: [],
              questionGroup: ["A1"],
              fileName: [],
              instanceQuestions: [],
              isAGeneralQuestion: false,
              autoCapture: false,
              allowAudioRecording: false,
              prefillFromEntityProfile: false,
              entityFieldName: "",
              isEditable: true,
              showQuestionInPreview: false,
              deleted: false,
              remarks: "",
              value: "",
              usedForScoring: "",
              questionType: "auto",
              canBeNotApplicable: "false",
              visibleIf: "",
              validation: {
                required: false,
              },
              file: {
                required: true,
                type: ["image/jpeg", "docx", "pdf", "ppt"],
                minCount: 0,
                maxCount: 10,
                caption: "FALSE",
              },
              externalId: "Q14_1616157220157-1616161753215",
              tip: "",
              hint: "",
              responseType: "text",
              modeOfCollection: "onfield",
              accessibility: "No",
              rubricLevel: "",
              sectionHeader: "",
              page: "p2",
              questionNumber: "10d",
              updatedAt: "2021-03-19T13:49:13.224Z",
              createdAt: "2021-03-19T13:41:46.377Z",
              __v: 0,
              createdFromQuestionId: "6054aa1a823d601f0af5c390",
              evidenceMethod: "OB",
              payload: {
                criteriaId: "6054abd9823d601f0af5c39f",
                responseType: "text",
                evidenceMethod: "OB",
                rubricLevel: "",
              },
              startTime: "",
              endTime: "",
              gpsLocation: "",
            },
          ],
          isAGeneralQuestion: false,
          autoCapture: false,
          allowAudioRecording: false,
          prefillFromEntityProfile: false,
          entityFieldName: "",
          isEditable: true,
          showQuestionInPreview: false,
          deleted: false,
          remarks: "",
          value: "",
          usedForScoring: "",
          questionType: "auto",
          canBeNotApplicable: "false",
          visibleIf: "",
          validation: {
            required: true,
          },
          instanceIdentifier: "Student",
          externalId: "Q10_1616157220157-1616161753198",
          tip: "",
          hint: "",
          responseType: "matrix",
          modeOfCollection: "onfield",
          accessibility: "No",
          rubricLevel: "",
          sectionHeader: "",
          page: "p2",
          questionNumber: "10",
          updatedAt: "2021-03-19T13:49:13.223Z",
          createdAt: "2021-03-19T12:33:46.601Z",
          __v: 0,
          createdFromQuestionId: "60549a2a823d601f0af5c368",
          evidenceMethod: "OB",
          payload: {
            criteriaId: "6054abd9823d601f0af5c39f",
            responseType: "matrix",
            evidenceMethod: "OB",
            rubricLevel: "",
          },
          startTime: "",
          endTime: "",
          gpsLocation: "",
          file: "",
        },
      ],
    },
    // {
    //   _id: "6054abd9823d601f0af5c391",
    //   question: ["Enter the date of observation", ""],
    //   isCompleted: false,
    //   showRemarks: false,
    //   options: [],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //     max: "",
    //     min: "",
    //   },
    //   dateFormat: "",
    //   externalId: "Q1_1616157220157-1616161753196",
    //   tip: "",
    //   hint: "",
    //   responseType: "date",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "1",
    //   updatedAt: "2021-03-19T13:49:13.223Z",
    //   createdAt: "2021-03-19T12:33:46.588Z",
    //   __v: 0,
    //   createdFromQuestionId: "60549a2a823d601f0af5c367",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39e",
    //     responseType: "date",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c393",
    //   question: ["Which class does your child study in?", ""],
    //   isCompleted: false,
    //   showRemarks: false,
    //   options: [],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //     IsNumber: "true",
    //   },
    //   externalId: "Q2_1616157220157-1616161753199",
    //   tip: "",
    //   hint: "",
    //   responseType: "number",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "2",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T12:33:46.611Z",
    //   __v: 0,
    //   createdFromQuestionId: "60549a2a823d601f0af5c369",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39e",
    //     responseType: "number",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c394",
    //   question: ["Are you currently living in the vicinity of the school?", ""],
    //   isCompleted: false,
    //   showRemarks: false,
    //   options: [
    //     {
    //       value: "R1",
    //       label: "Yes",
    //     },
    //     {
    //       value: "R2",
    //       label: "No",
    //     },
    //   ],
    //   sliderOptions: [],
    //   children: ["6054abd9823d601f0af5c395"],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //   },
    //   externalId: "Q3_1616157220157-1616161753202",
    //   tip: "Use the name of the locality where the school is",
    //   hint: "",
    //   responseType: "radio",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "3",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T12:33:46.622Z",
    //   __v: 0,
    //   createdFromQuestionId: "60549a2a823d601f0af5c36a",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39e",
    //     responseType: "radio",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c395",
    //   question: ["Are you planning to come back?", ""],
    //   isCompleted: false,
    //   showRemarks: false,
    //   options: [
    //     {
    //       value: "R1",
    //       label: "Yes",
    //     },
    //     {
    //       value: "R2",
    //       label: "No",
    //     },
    //   ],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: [
    //     {
    //       operator: "===",
    //       value: ["R2"],
    //       _id: "6054abd9823d601f0af5c394",
    //     },
    //   ],
    //   validation: {
    //     required: false,
    //   },
    //   externalId: "Q4_1616157220157-1616161753203",
    //   tip: "",
    //   hint: "This becomes a risk if the answer is no",
    //   responseType: "radio",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "4",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T12:33:46.633Z",
    //   __v: 0,
    //   createdFromQuestionId: "60549a2a823d601f0af5c36b",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39e",
    //     responseType: "radio",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c396",
    //   question: ["What type of device is available at home?", ""],
    //   isCompleted: false,
    //   showRemarks: true,
    //   options: [
    //     {
    //       value: "R1",
    //       label: "Simple mobile phone without internet/data pack",
    //     },
    //     {
    //       value: "R2",
    //       label: "Smart phone with internet/data pack",
    //     },
    //     {
    //       value: "R3",
    //       label: "Smart phone without internet/data pack",
    //     },
    //     {
    //       value: "R4",
    //       label: "TV",
    //     },
    //     {
    //       value: "R5",
    //       label: "Radio",
    //     },
    //   ],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //   },
    //   file: {
    //     required: true,
    //     type: ["image/jpeg", "docx", "pdf", "ppt"],
    //     minCount: 0,
    //     maxCount: 10,
    //     caption: "FALSE",
    //   },
    //   externalId: "Q5_1616157220157-1616161753205",
    //   tip: "",
    //   hint: "The devices that are available or can be easily arranged in the household.",
    //   responseType: "multiselect",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "5",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T12:33:46.646Z",
    //   __v: 0,
    //   createdFromQuestionId: "60549a2a823d601f0af5c36c",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39e",
    //     responseType: "multiselect",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c397",
    //   question: ["Does the child have a quiet place to study?", ""],
    //   isCompleted: false,
    //   showRemarks: true,
    //   options: [
    //     {
    //       value: "R1",
    //       label: "Yes",
    //     },
    //     {
    //       value: "R2",
    //       label: "No",
    //     },
    //   ],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //   },
    //   externalId: "Q6_1616157220157-1616161753206",
    //   tip: "",
    //   hint: "",
    //   responseType: "radio",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "6",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T12:33:46.657Z",
    //   __v: 0,
    //   createdFromQuestionId: "60549a2a823d601f0af5c36d",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39e",
    //     responseType: "radio",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c398",
    //   question: ["Were you able to enrol your child in courses on DIKSHA?", ""],
    //   isCompleted: false,
    //   showRemarks: false,
    //   options: [
    //     {
    //       value: "R1",
    //       label: "Yes",
    //     },
    //     {
    //       value: "R2",
    //       label: "No",
    //     },
    //   ],
    //   sliderOptions: [],
    //   children: ["6054abd9823d601f0af5c399"],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //   },
    //   externalId: "Q7_1616157220157-1616161753207",
    //   tip: "",
    //   hint: "",
    //   responseType: "radio",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "7",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T12:33:46.677Z",
    //   __v: 0,
    //   createdFromQuestionId: "60549a2a823d601f0af5c36e",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39e",
    //     responseType: "radio",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c399",
    //   question: [
    //     "What are the challenges that you are facing in enrolment?",
    //     "",
    //   ],
    //   isCompleted: false,
    //   showRemarks: true,
    //   options: [
    //     {
    //       value: "R1",
    //       label: "Not able to use the app",
    //     },
    //     {
    //       value: "R2",
    //       label: "Not aware of classrooms on DIKSHA",
    //     },
    //     {
    //       value: "R3",
    //       label: "Not aware of the enrolment process in the classroom",
    //     },
    //     {
    //       value: "R4",
    //       label: "Not aware of enrolment process in the courses",
    //     },
    //     {
    //       value: "R5",
    //       label: "Don’t find the courses useful",
    //     },
    //     {
    //       value: "R6",
    //       label: "Others",
    //     },
    //   ],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: [
    //     {
    //       operator: "===",
    //       value: ["R2"],
    //       _id: "6054abd9823d601f0af5c398",
    //     },
    //   ],
    //   validation: {
    //     required: true,
    //   },
    //   externalId: "Q8_1616157220157-1616161753209",
    //   tip: "",
    //   hint: "",
    //   responseType: "multiselect",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "8",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T12:33:46.689Z",
    //   __v: 0,
    //   createdFromQuestionId: "60549a2a823d601f0af5c36f",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39e",
    //     responseType: "multiselect",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c39a",
    //   question: [
    //     "On basis of the responses received above,  do you think this student is a potential drop out?",
    //     "",
    //   ],
    //   isCompleted: false,
    //   showRemarks: true,
    //   options: [
    //     {
    //       value: "R1",
    //       label: "Yes",
    //     },
    //     {
    //       value: "R2",
    //       label: "No",
    //     },
    //   ],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //   },
    //   externalId: "Q9_1616157220157-1616161753210",
    //   tip: "Fill this based on the  parents' answers",
    //   hint: "",
    //   responseType: "radio",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p1",
    //   questionNumber: "9",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T12:33:46.706Z",
    //   __v: 0,
    //   createdFromQuestionId: "60549a2a823d601f0af5c370",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39e",
    //     responseType: "radio",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c39b",
    //   question: ["How would you rate the course taken?", ""],
    //   isCompleted: false,
    //   showRemarks: false,
    //   options: [],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //     max: "10",
    //     min: "5",
    //   },
    //   externalId: "Q12_1616157220157-1616161753212",
    //   tip: "",
    //   hint: "",
    //   responseType: "slider",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p2",
    //   questionNumber: "10b",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T13:41:46.341Z",
    //   __v: 0,
    //   createdFromQuestionId: "6054aa1a823d601f0af5c38e",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39f",
    //     responseType: "slider",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c39c",
    //   question: ["How many courses have you taken?", ""],
    //   isCompleted: false,
    //   showRemarks: false,
    //   options: [],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //     IsNumber: "true",
    //   },
    //   externalId: "Q13_1616157220157-1616161753214",
    //   tip: "",
    //   hint: "",
    //   responseType: "number",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p2",
    //   questionNumber: "10c",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T13:41:46.360Z",
    //   __v: 0,
    //   createdFromQuestionId: "6054aa1a823d601f0af5c38f",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39f",
    //     responseType: "number",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    //   file: "",
    // },
    // {
    //   _id: "6054abd9823d601f0af5c39d",
    //   question: ["Which courses did you go through?", ""],
    //   isCompleted: false,
    //   showRemarks: false,
    //   options: [],
    //   sliderOptions: [],
    //   children: [],
    //   questionGroup: ["A1"],
    //   fileName: [],
    //   instanceQuestions: [],
    //   isAGeneralQuestion: false,
    //   autoCapture: false,
    //   allowAudioRecording: false,
    //   prefillFromEntityProfile: false,
    //   entityFieldName: "",
    //   isEditable: true,
    //   showQuestionInPreview: false,
    //   deleted: false,
    //   remarks: "",
    //   value: "",
    //   usedForScoring: "",
    //   questionType: "auto",
    //   canBeNotApplicable: "false",
    //   visibleIf: "",
    //   validation: {
    //     required: true,
    //     regex: "^[A-Za-z]+$",
    //   },
    //   file: {
    //     required: true,
    //     type: ["image/jpeg", "docx", "pdf", "ppt"],
    //     minCount: 0,
    //     maxCount: 10,
    //     caption: "FALSE",
    //   },
    //   externalId: "Q14_1616157220157-1616161753215",
    //   tip: "",
    //   hint: "",
    //   responseType: "text",
    //   modeOfCollection: "onfield",
    //   accessibility: "No",
    //   rubricLevel: "",
    //   sectionHeader: "",
    //   page: "p2",
    //   questionNumber: "10d",
    //   updatedAt: "2021-03-19T13:49:13.224Z",
    //   createdAt: "2021-03-19T13:41:46.377Z",
    //   __v: 0,
    //   createdFromQuestionId: "6054aa1a823d601f0af5c390",
    //   evidenceMethod: "OB",
    //   payload: {
    //     criteriaId: "6054abd9823d601f0af5c39f",
    //     responseType: "text",
    //     evidenceMethod: "OB",
    //     rubricLevel: "",
    //   },
    //   startTime: "",
    //   endTime: "",
    //   gpsLocation: "",
    // },
  ];
}
