export const Response = {
    batchlistSucessData: {
        'lastName': 'Kumar',
        'webPages': [],
        'tcStatus': null,
        'education': [],
        'gender': null,
        'regOrgId': null,
        'subject': [],
        'roles': [
            'PUBLIC'
        ],
        'language': [],
        'updatedDate': null,
        'skills': [],
        'isDeleted': null,
        'organisations': [],
        'provider': null,
        'countryCode': '+91',
        'id': '2a25480b-03f1-4772-80a1-dc65bb002e3c',
        'tempPassword': null,
        'email': '',
        'identifier': '2a25480b-03f1-4772-80a1-dc65bb002e3c',
        'thumbnail': null,
        'address': [],
        'jobProfile': [],
        'profileSummary': null,
        'tcUpdatedDate': null,
        'avatar': null,
        'rootOrgId': 'ORG_001',
        'badges': [],
        'emailVerified': false,
        'firstName': 'Amit',
        'lastLoginTime': null,
        'createdDate': '2017-11-29 11:03:12:000+0000',
        'createdBy': '',
        'phone': '',
        'dob': null,
        'grade': [],
        'currentLoginTime': null,
        'location': 'location',
        'status': 1
    }
};
