name: CI/CD

on:
  push:
    branches:
      - "*" # Trigger on push to any branch
  pull_request:
    branches:
      - "*" # Trigger on pull request to any branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install client dependencies
      - name: Install client dependencies
        working-directory: src/app/client
        run: yarn install --no-progress --production=true

      # Build the client
      - name: Build client
        working-directory: src/app/client
        run: npm run build

      # List all files after the build
      - name: List all files after build
        working-directory: src/app/client
        run: find . -type f

      # Check if the dist directory exists and list its contents
      - name: Check if dist directory exists and list contents
        working-directory: src/app/client
        run: |
          if [ -d dist ]; then
            echo "dist directory exists. Listing contents:"
            ls -l dist
          else
            echo "dist directory does not exist"
          fi

      # Move index.html to index.ejs if it exists
      - name: Move index.html to index.ejs if it exists
        working-directory: src/app/client
        run: |
          if [ -f dist/index.html ]; then
            mv dist/index.html dist/index.ejs
          else
            echo "File dist/index.html does not exist"
          fi

      # Set up server directories
      - name: Set up server directories
        run: mkdir -p $GITHUB_WORKSPACE/app_dist

      # Copy server files to the destination directory
      - name: Copy server files
        run: |
          cp -r src/app/libs src/app/helpers src/app/proxy src/app/resourcebundles src/app/package.json src/app/framework.config.js src/app/sunbird-plugins src/app/routes src/app/constants src/app/controllers src/app/server.js $GITHUB_WORKSPACE/app_dist/
        shell: /usr/bin/bash -e {0}

      # Install server dependencies
      - name: Install server dependencies
        working-directory: ${{ github.workspace }}/app_dist
        run: yarn install --ignore-engines --no-progress --production=true

      # Run server build script
      - name: Run server build script
        working-directory: ${{ github.workspace }}/app_dist
        run: node helpers/resourceBundles/build.js -task="phraseAppPull"
      # Execute test cases using JEST
      # - name: Execute test cases using JEST
      #   working-directory: src/app/client
      #   run: |
      #     yarn config set ignore-engines true
      #     yarn install
      #     npm run test:ci

      # Install Sonar Scanner..
      - name: Install Sonar Scanner
        run: |
          cd /tmp
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          sudo apt-get install -y unzip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          cd -

      - name: Run Sonar Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd ~ && /tmp/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
             -Dsonar.projectKey=Sunbird-Ed_SunbirdEd-portal \
             -Dsonar.organization=sunbird-ed \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.login=$SONAR_TOKEN \
             -Dsonar.exclusions=**/node_modules/**,**/environments/**,**/assets/**, **/*.module.ts, src/assets/**,src/app/client/src/assets/**,src/thidparty/**,src/app/modules/offline/**,src/app/client/src/**/*.spec.ts,src/app/client/src/**/*.spec.data.ts,src/app/client/src/**/*.module.ts,src/app/tenant/**,src/app/sunbird-plugins/**,src/app/assets/**, src/app/client/src/**/*.mock.data.ts, src/app/modules/cbse-program/**/**, src/app/plugins/profile/**/**, src/app/modules/core/services/tenant/**, \
                                src/app/plugins/profile/components/profile-page/profile-page.component.ts, src/app/modules/core/services/tenant/tenant.service.ts,src/app/modules/certificate/components/certificate-details/certificate-details.component.ts, src/app/modules/certificate/**/** \
